-- <copyright file="TO_CHAR_FORMAT_ELEMENTS_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

-----------------------------------------------------------------------------
-- The following UDFs emulate the functionality of multiple format elements
-- related to the TO_CHAR function.
-----------------------------------------------------------------------------


CREATE OR REPLACE FUNCTION PUBLIC.APPLY_CASE_UDF(RESULTVALUE VARCHAR, RESULTCASE STRING)
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
	CASE RESULTCASE
		WHEN 'uppercase' THEN UPPER(RESULTVALUE)
		WHEN 'lowercase' THEN LOWER(RESULTVALUE)
		ELSE RESULTVALUE
	END
$$;

CREATE OR REPLACE FUNCTION PUBLIC.CENTURY_UDF(INPUT TIMESTAMP_TZ)
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
	CASE WHEN MOD(YEAR(INPUT), 100) = 0
    THEN
        (TRUNC(YEAR(INPUT) / 100)):: VARCHAR
    ELSE
        (TRUNC(YEAR(INPUT) / 100) + 1):: VARCHAR
    END
$$;

CREATE OR REPLACE FUNCTION PUBLIC.DAYNAME_LONG_UDF(INPUT TIMESTAMP_TZ, RESULTCASE VARCHAR)
RETURNS VARCHAR(9)
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    RPAD(PUBLIC.APPLY_CASE_UDF(
		DECODE(DAYNAME(INPUT)
			, 'Sun' , 'Sunday'
			, 'Mon' , 'Monday'
			, 'Tue' , 'Tuesday'
			, 'Wed' , 'Wednesday'
			, 'Thu' , 'Thursday'
			, 'Fri' , 'Friday'
			, 'Sat' , 'Saturday'
			,'None'),
			RESULTCASE
	), 9)
$$;


CREATE OR REPLACE FUNCTION PUBLIC.DAY_OF_YEAR_ISO_UDF(INPUT TIMESTAMP_TZ)
RETURNS VARCHAR
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
	(DAYOFWEEKISO(INPUT) + (WEEKISO(INPUT) - 1) * 7) :: VARCHAR
$$;

CREATE OR REPLACE FUNCTION PUBLIC.FULL_MONTH_NAME_UDF(INPUT TIMESTAMP_TZ, RESULTCASE VARCHAR)
RETURNS VARCHAR(9)
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    RPAD(PUBLIC.APPLY_CASE_UDF(TO_CHAR(INPUT, 'MMMM'), RESULTCASE), 9)
$$;

CREATE OR REPLACE FUNCTION PUBLIC.ISO_YEAR_PART_UDF(INPUT TIMESTAMP_TZ, DIGITS INTEGER)
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
	SUBSTR(ABS(YEAROFWEEKISO(INPUT)), 5 - DIGITS)
$$;

CREATE OR REPLACE FUNCTION PUBLIC.JULIAN_DAY_UDF(INPUT TIMESTAMP_TZ)
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    CASE WHEN MONTH(INPUT) > 2
    THEN
        (TRUNC(DAY(INPUT) + (153 * (MONTH(INPUT) - 3) + 2) / 5 + 365.2425 * (YEAR(INPUT) + 4800) - 32045)):: VARCHAR
    ELSE
        (TRUNC(DAY(INPUT) + (153 * (MONTH(INPUT) + 9) + 2) / 5 + 365.2425 * (YEAR(INPUT) + 4799) - 32045)):: VARCHAR
    END
$$;


CREATE OR REPLACE FUNCTION PUBLIC.MONTH_SHORT_UDF(INPUT TIMESTAMP_TZ, RESULTCASE VARCHAR)
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    PUBLIC.APPLY_CASE_UDF(TO_CHAR(INPUT, 'Mon'), RESULTCASE)
$$;

CREATE OR REPLACE FUNCTION PUBLIC.ROMAN_NUMERALS_MONTH_UDF(INPUT TIMESTAMP_TZ, RESULTCASE VARCHAR)
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    PUBLIC.APPLY_CASE_UDF(
		DECODE(MONTH(INPUT),
			1, 'I',
			2, 'II',
			3, 'III',
			4, 'IV',
			5, 'V',
			6, 'VI',
			7, 'VII',
			8, 'VIII',
			9, 'IX',
			10, 'X',
			11, 'XI',
			12, 'XII'
    	),
		RESULTCASE
	)
$$;

CREATE OR REPLACE FUNCTION PUBLIC.SECONDS_PAST_MIDNIGHT_UDF(INPUT TIMESTAMP_TZ)
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    (HOUR(INPUT) * 3600 + MINUTE(INPUT) * 60 + SECOND(INPUT)):: VARCHAR
$$;

CREATE OR REPLACE FUNCTION PUBLIC.WEEK_OF_MONTH_UDF(INPUT TIMESTAMP_TZ)
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    (CEIL(DAY(INPUT) / 7)):: VARCHAR
$$;

CREATE OR REPLACE FUNCTION PUBLIC.YEAR_PART_UDF(INPUT TIMESTAMP_TZ, DIGITS INTEGER)
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    SUBSTR(ABS(YEAR(INPUT)), 5 - DIGITS)
$$;

CREATE OR REPLACE FUNCTION PUBLIC.YEAR_WITH_COMMA_UDF(INPUT TIMESTAMP_TZ)
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    INSERT(ABS(YEAR(INPUT)), 2, 0, ',')
$$;