-- <copyright file="YEARS_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

-- =============================================
-- DESCRIPTION: UDF THAT REPRODUCES SYBASE YEARS FUNCTIONALITY
-- PARAMETERS:
--      FIRST_DATE: TIMESTAMP
--      SECOND_DATE: TIMESTAMP
-- RETURNS: NUMBER OF YEARS BETWEEN FIRST_DATE AND SECOND_DATE IF SECOND_DATE IS NOT SENT
--          0000-01-01 IS USED LIKE INITIAL DATE AS SYBASE PERFORMS.
-- EXAMPLE:
--  SELECT YEARS_UDF('2021-02-14'); -- RETURNS THE YEARS BETWEEN 0000-01-01 AND 2021-02-14
--  SELECT YEARS_UDF('2021-02-14', '2022-02-14'); -- RETURNS THE YEARS BETWEEN 2021-02-14 AND 2022-02-14
-- =============================================

CREATE OR REPLACE FUNCTION PUBLIC.YEARS_UDF(FIRST_DATE TIMESTAMP, SECOND_DATE TIMESTAMP DEFAULT NULL)
RETURNS INT
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    CASE
        WHEN SECOND_DATE IS NULL THEN
        DATEDIFF(YEAR, DATE_FROM_PARTS(0, 1, 1), FIRST_DATE)
    ELSE
         DATEDIFF(YEAR, FIRST_DATE, SECOND_DATE)
$$;

-- =============================================
-- DESCRIPTION: UDF THAT REPRODUCES SYBASE YEARS FUNCTIONALITY
-- PARAMETERS:
--      INPUT: TIMESTAMP
--      AMOUNT: INTEGER
-- RETURNS: ADDS THE AMOUNT OF YEARS PROVIDED.
-- EXAMPLE:
--  SELECT YEARS_UDF(1, '2021-02-14'); -- 2022-02-14
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.YEARS_UDF(INPUT TIMESTAMP, AMOUNT INTEGER)
RETURNS TIMESTAMP
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    DATEADD(YEAR, AMOUNT, INPUT)
$$;