# 0: Mark as supported if no rule handles node.
# 1: Mark as NOT supported if no rule handles node.

# Notes:
#   - PythonSnowConvert Rules have precedence over the contents of this file.
#   - Everything is considered to be "1: Mark as NOT supported if no rule handles node" by default, unless specified otherwise.
#   - For consistency purposes, all nodes should be in this file, even when commented out.
Py:
# Add : null
# And : null : null
# AnnotatedRhs : null : null
# AnnotatedStars : null : null
# AnnotatedRhsYield : null : null
# Annotation : null : null
# ArgExpr : null : null
# ArgNamedExpr : null : null
# Args : null : null
# ArgsExprs : null : null
# ArgStarExpr : null : null
# ArgsKwargs : null : null
# Argument : null : null
# ArgumentList : null
# Arguments : null
# ArrowExpr : null
# AsName : null
# AssertStat : null
# AssignAnnotatedRhs : null
# AssignAugAssign : null
# AssignExpr : null
# Assignment : null
# AssignName : null
# AssignOperator : null
# AssignSingle : null
# AssignSingleSubs : null
# AssignStar : null
# AsStarTarget : null
# Async : null
# Atom : null
# AtomDict : null
# AtomDictComp : null
# AtomElem : null
# AtomEllipsis : null
# AtomGenExp : null
# AtomGroup : null
# AtomList : null
# AtomListComp : null
# AtomLiteral : null
# AtomName : null
# AtomSet : null
# AtomSetComp : null
# AtomStrings : null
# AtomTuple : null
# AtomWithKind : null
# AugAssign : null
# Await : null
# BinAnd : null
# BinaryOperation : null
# BinOr : null
# BitwiseAnd : null
# BitwiseAndOpShift : null
# BitwiseAndShift : null
# BitwiseOr : null
# BitwiseOrOpXor : null
# BitwiseOrXor : null
# BitwiseXor : null
# BitwiseXorAnd : null
# BitwiseXorOpAnd : null
# Block : null
# Break : null
# Class : null
# ClassBody : null
# ClassDef : null
# Comma : null
# CommaExpr : null
# Comment : null
# Compound : null
# ColonExpr : null
# CommaKwargs : null
# CompareOp : null
# CompareOpBitwiseOrPair : null
# CompareOperator : null
# Comparison : null
# Conjunction : null
# Continue : null
# Decorator : null
# Decorators : null
# DefParameter : null
# Default : null
# DelStat : null
# DelTarget : null
# DelTargets : null
# DelTAtom : null
# DelTAtomTarget : null
# DelTAtomTargets : null
# DelTAtomTargetsB : null
# DelTAtomTargetsP : null
# DelTName : null
# DelTPrimaryBracedSlices : null
# DelTPrimaryDotName : null
# Dict : null
# DictComp : null
# DictExpr : null
# Disjunction : null
# Distinct : null
# Division : null
# Dot : null
# DotName : null
# DotOrEllipsisPunctuator : null
# DotOrEllipsis : null
# DottedAsName : null
# DottedName : null
# DoubleStarExpr : null
# DoubleStarFactor : null
# DoubleStarKvpair : null
# DoubleStarKvpairDouble : null
# DoubleStarKvpairPair : null
# DoubleStarKvpairs : null
# ElifStat : null
# ElifStatElif : null
# ElifStatElse : null
# Else : null
# EmbeddedExpr : null
# Emit : null
# EmptyStat : null
# Eq : null
# Except : null
# Excepts : null
# Extensions : null
# Expr : null
# ExprAtom : null
# ExprAtomExpr : null
# ExprAsName : null
# ExprDisjunction : null
# ExprMemberAccess : null
# ExprSequence : null
# ExprStat : null
# Factor : null
# FactorOp : null
# FactorOperator : null
# FactorPower : null
# Finally : null
# FloorDivision : null
# For : null
# ForIfClause : null
# ForIfClauses : null
# FromExpr : null
# FuncDef : null
# FuncTypeComment : null
# GenExp : null
# GlobalStat : null
# GreaterThan : null
# GreaterThanOrEqual : null
# Group : null
# GroupNamedExpr : null
# GroupYieldExpr : null
# If : null
# IfElif : null
# IfElse : null
# IfDisjuntion : null
# IfKeyword : null
# Import : null
# ImportFrom : null
# ImportFromAsName : null
# ImportFromAsNames : null
# ImportFromAsNameSeq : null
# ImportFromAsNamesPSeq : null
# ImportFromAsStar : null
# ImportFromDot : null
# ImportFromDotName : null
# ImportFromTargets : null
# ImportName : null
# In : null
# Inheritance : null
# Inversion : null
# InversionComparison : null
# InversionNot : null
# Is : null
# Keyword : null
# Kvpair : null
# Kwarg : null
# KwargOrDoubleStar : null
# KwargOrDoubleStarDoubleStar : null
# KwargOrDoubleStarKwarg : null
# KwargOrStar : null
# KwargOrStarKwarg : null
# KwargOrStarStar : null
# Kwargs : null
# KwargsDoubleStar : null
# KwargsDoubleStarSeq : null
# KwargsStar : null
# KwargsStarDoubleStar : null
# KwargsStarSeq : null
# Kwds : null
# LambdaKwds : null
# LambdaParam : null
# LambdaParamMaybeDefault : null
# LambdaParamNoDefault : null
# LambdaParamsStarEtc : null
# LambdaParamWithDefault : null
# LambdaSlashNoDefault : null
# LambdaSlashWithDefault : null
# LambdaStarEtc : null
# LambdaStarEtcKwds : null
# LambdaStarEtcStar : null
# LambdaStarEtcStarComma : null
# LanguageServices : null
# LessThan : null
# LessThanOrEqual : null
# Literal : null
# LiteralString : null
# LiteralValue : null
# List : null
# ListComp : null
# ListExpr : null
# MigrationNote : null
# Modulo : null
# Name : null
# NamedExpr : null
# NamedExprExpr : null
# NamedExprName : null
# Negate : null
# NonLocalStat : null
# Not : null
# Operator : null
# Or : null
# Param : null
# ParamMaybeDefault : null
# ParamMaybeDefaultComma : null
# ParamNoDefault : null
# ParamNoDefaultComma : null
# Parameter : null
# ParameterList : null
# Params : null
# ParamsNoDefault : null
# ParamsSlashNoDefault : null
# ParamsSlashWithDefault : null
# ParamsStarEtc : null
# ParamsWithDefault : null
# ParamWithDefault : null
# ParamWithDefaultComma : null
# Pass : null
# Power : null
# Primary : null
# Program : null
# Punctuator : null
# Raise : null
# RaiseExpr : null
# Return : null
# Set : null
# SetComp : null
# ShiftExpr : null
# ShiftExprOpSum : null
# ShiftExprSum : null
# ShiftOperator : null
# SimpleArgument : null
# SimpleLiteral : null
# SingleAccess : null
# SingleSubsAttribTargetBrace : null
# SingleSubsAttribTargetDot : null
# SingleSubscriptAttributeTarget : null
# SingleTarget : null
# SingleTargetName : null
# SingleTargetPSingle : null
# SingleTargetSingleSubscript : null
# SlashComma : null
# SlashCommaOrSlash : null
# SlashLARPar : null
# SlashNoDefault : null
# SlashWithDefault : null
# Slice : null
# SliceColon : null
# SliceExpr : null
# SliceMultiple : null
# Slices : null
# SliceSingle : null
# Source : null
# SourceInstance : null
# Star : null
# StarAtom : null
# StarAtomBStar : null
# StarAtomName : null
# StarAtomPStar : null
# StarAtomPTarget : null
# StarBitwiseOr : null
# StarEtc : null
# StarEtcKwds : null
# StarEtcMaybeDefault : null
# StarEtcNoDefault : null
# StarExpr : null
# StarExprExpr : null
# StarExprs : null
# StarExprStar : null
# StarNamedExpr : null
# StarNamedExprs : null
# StarNameExprNamed : null
# StarNameExprStar : null
# StarTarget : null
# StarTargets : null
# StarTargetsAssign : null
# StarTargetsListSeq : null
# StarTargetsSeq : null
# StarTargetsSingle : null
# StarTargetStar : null
# StarTargetsTupleSeq : null
# StarTargetsTupleSequence : null
# StarTargetsTupleSingle : null
# StarTargetWithStarAtom : null
# StarredExpr : null
# Stat : null
# SubscriptExpr : null
# Substraction : null
# Sum : null
# SumOperator : null
# SumOpTerm : null
# SumTerm : null
# Tail : null
# TailArguments : null
# TailBSlices : null
# TailDotName : null
# TailGenExp : null
# TargetWithStarAtom : null
# Term : null
# TermFactor : null
# TermOperator : null
# TermOpFactor : null
# TestDelStatSemiColon : null
# TestTPrimaryDotNameComma : null
# TestTPSDotNameLpar : null
# TPrimary : null
# TPrimaryBracedSlices : null
# TPrimaryDotName : null
# TPrimarySuffix : null
# TPSBracedSlices : null
# TPSDotName : null
# TPSGenExp : null
# TPSPar : null
# TrailerExpr : null
# TrailerExprSeq : null
# Tuple : null
# TupleExprSeq : null
# TWSABrace : null
# TWSADot : null
# TWSAStar : null
# TypeComment : null
# TypeCommentSuffix : null
# TypeCommentSuffixComma : null
# TypeCommentSuffixSingle : null
# Try : null
# TryExcepts : null
# TryFinally : null
# UnaryOperator : null
# UnsupportedExpr : null
# UnsupportedStat : null
# While : null
# With : null
# WithComma : null
# WithItem : null
# WithPar : null
# YieldExpr : null
# YieldExprFrom : null
# YieldExprStar : null
# YieldStat : null