-- <copyright file="TO_CHAR_FORMAT_ELEMENTS_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

-----------------------------------------------------------------------------
-- The following UDFs emulate the functionality of multiple format elements
-- related to the TO_CHAR function from PostgreSQL.
-----------------------------------------------------------------------------


CREATE OR REPLACE FUNCTION PUBLIC.APPLY_CASE_UDF(RESULTVALUE VARCHAR, RESULTCASE STRING)
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
	CASE RESULTCASE
		WHEN 'uppercase' THEN UPPER(RESULTVALUE)
		WHEN 'lowercase' THEN LOWER(RESULTVALUE)
		ELSE RESULTVALUE
	END
$$;


CREATE OR REPLACE FUNCTION PUBLIC.DAYNAME_SHORT_UDF(INPUT TIMESTAMP_TZ, RESULTCASE VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    PUBLIC.APPLY_CASE_UDF(DAYNAME(INPUT), RESULTCASE)
$$;

CREATE OR REPLACE FUNCTION PUBLIC.DAY_OF_WEEK_UDF(INPUT TIMESTAMP_TZ)
RETURNS VARCHAR
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
	(DAYOFWEEK(INPUT) + 1) :: VARCHAR
$$;


CREATE OR REPLACE FUNCTION PUBLIC.ERA_INDICATORS_UDF(INPUT TIMESTAMP_TZ, RESULTCASE STRING)
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
	PUBLIC.APPLY_CASE_UDF(IFF(DATE_PART(YEAR, INPUT) < 1, 'BC', 'AD'), RESULTCASE)
$$;

CREATE OR REPLACE FUNCTION PUBLIC.ERA_INDICATORS_WITH_POINTS_UDF(INPUT TIMESTAMP_TZ, RESULTCASE STRING)
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
	PUBLIC.APPLY_CASE_UDF(IFF(DATE_PART(YEAR, INPUT) < 1, 'B.C.', 'A.D.'), RESULTCASE)
$$;

CREATE OR REPLACE FUNCTION PUBLIC.MERIDIAN_INDICATORS_UDF(INPUT TIMESTAMP_TZ, RESULTCASE STRING)
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
	PUBLIC.APPLY_CASE_UDF(IFF(DATE_PART(HOUR, INPUT) < 12, 'AM', 'PM'), RESULTCASE)
$$;

CREATE OR REPLACE FUNCTION PUBLIC.MERIDIAN_INDICATORS_WITH_POINTS_UDF(INPUT TIMESTAMP_TZ, RESULTCASE STRING)
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
	PUBLIC.APPLY_CASE_UDF(IFF(DATE_PART(HOUR, INPUT) < 12, 'A.M.', 'P.M.'), RESULTCASE)
$$;
       
CREATE OR REPLACE FUNCTION PUBLIC.WEEK_NUMBER_UDF(INPUT TIMESTAMP_TZ)
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    (CEIL(DAYOFYEAR(INPUT) / 7)):: VARCHAR
$$;