-- <copyright file="DATE_DIFFERENCE_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

-- =============================================
-- DESCRIPTION: UDF THAT REPRODUCES DATETIME TERADATA'S SUBTRACTION
-- PARAMETERS:
--  MINUEND: TIMESTAMP - DATE SUBTRACTED FROM
--  SUBTRAHEND: TIMESTAMP - DATE SUBTRACTED
--  INPUT_PART: VARCHAR - PARTS TO BE RETURNED (EQUIVALENT TO TERADATA'S INTERVAL)
-- RETURNS: FORMATED VARCHAR WITH INPUT_PART REQUESTED 
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.TIMESTAMP_DIFFERENCE_UDF
(MINUEND TIMESTAMP, SUBTRAHEND TIMESTAMP, INPUT_PART VARCHAR)
RETURNS VARCHAR 
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
   DECODE(INPUT_PART,
           'YEAR',             TO_VARCHAR(DATEDIFF(YEAR, SUBTRAHEND, MINUEND)),
           'MONTH',            TO_VARCHAR(DATEDIFF(MONTH, SUBTRAHEND, MINUEND)),
           'YEAR TO MONTH',    CASE WHEN SUBTRAHEND>MINUEND AND TRUNC(DATEDIFF(MONTH, SUBTRAHEND, MINUEND)/12) >= 0 THEN '-' ELSE '' END || TO_VARCHAR(TRUNC(DATEDIFF(MONTH, SUBTRAHEND, MINUEND)/12)) ||'-'|| REPLACE(TO_VARCHAR(DATEDIFF(MONTH, SUBTRAHEND, MINUEND)%12,'FM00'),'-',''),
           'DAY',              TO_VARCHAR(TRUNC(DATEDIFF(SECONDS, SUBTRAHEND, MINUEND)/(86400))),
           'DAY TO HOUR',      CASE WHEN SUBTRAHEND>MINUEND THEN '-' ELSE '' END || REPLACE(TO_VARCHAR(TRUNC(DATEDIFF(SECONDS, SUBTRAHEND, MINUEND)/(86400))) || ' ' || TO_CHAR(TIMEDIFF('HOUR', LEAST(MINUEND::TIME,SUBTRAHEND::TIME), GREATEST(MINUEND::TIME, SUBTRAHEND::TIME)),'FM00'),'-',''),
           'DAY TO MINUTE',    CASE WHEN SUBTRAHEND>MINUEND THEN '-' ELSE '' END || REPLACE(TO_VARCHAR(TRUNC(DATEDIFF(SECONDS, SUBTRAHEND, MINUEND)/(86400))) || ' ' || TO_CHAR(TRUNC(MOD((DATEDIFF('SECOND', SUBTRAHEND, MINUEND)),86400)/3600),'FM00') || ':' || TO_CHAR(TRUNC(MOD((DATEDIFF('SECOND', SUBTRAHEND, MINUEND)),3600)/60),'FM00'),'-',''),
           'DAY TO SECOND',    CASE WHEN SUBTRAHEND>MINUEND THEN '-' ELSE '' END || REPLACE(TO_VARCHAR(TRUNC(DATEDIFF(SECONDS, SUBTRAHEND, MINUEND)/(86400))) || ' ' || TO_CHAR(TRUNC(MOD((DATEDIFF('SECOND', SUBTRAHEND, MINUEND)),86400)/3600),'FM00') || ':' || TO_CHAR(TRUNC(MOD((DATEDIFF('SECOND', SUBTRAHEND, MINUEND)),3600)/60),'FM00') || ':'|| TO_CHAR((DATEDIFF('MILLISECOND', SUBTRAHEND, MINUEND)/1000)%60,'FM00.000000'),'-',''),
           'HOUR',             TO_VARCHAR(DATEDIFF(HOUR, SUBTRAHEND, MINUEND)),
           'HOUR TO MINUTE',   TO_CHAR(TRUNC((DATEDIFF('SECOND', SUBTRAHEND, MINUEND))/3600),'FM99999999999999999999999999999999') || ':' ||  REPLACE(TO_CHAR(TRUNC(MOD((DATEDIFF('SECOND', SUBTRAHEND, MINUEND)),3600)/60),'FM00'),'-','') ,
           'HOUR TO SECOND',   TO_CHAR(TRUNC((DATEDIFF('SECOND', SUBTRAHEND, MINUEND))/3600),'FM99999999999999999999999999999999') || ':' ||  REPLACE(TO_CHAR(TRUNC(MOD((DATEDIFF('SECOND', SUBTRAHEND, MINUEND)),3600)/60),'FM00'),'-','') || ':' || REPLACE(TO_CHAR((DATEDIFF('MILLISECOND', SUBTRAHEND, MINUEND)/1000)%60,'FM00.000000'),'-',''),
           'MINUTE',           TO_VARCHAR(DATEDIFF(MINUTE, SUBTRAHEND, MINUEND)),
           'MINUTE TO SECOND', TO_CHAR(TRUNC((DATEDIFF('SECOND', SUBTRAHEND, MINUEND))/60),'FM99999999999999999999999999999999') || ':' || REPLACE(TO_CHAR((DATEDIFF('MILLISECOND', SUBTRAHEND, MINUEND)/1000)%60,'FM00.000000'),'-',''),
           'SECOND',           TO_CHAR((DATEDIFF('MILLISECOND', SUBTRAHEND, MINUEND)/1000)%60,'FM99999999999999999999999999999999.000000')
            )
$$;

-- =============================================
-- DESCRIPTION: EXTRACTS 'DATE PART' FROM THE RESULT OF THE SUBTRACTION 'MINUEND' - 'SUBTRAHEND',
--  CONVERTING IT TO AN EXACT NUMERIC VALUE
-- PARAMETERS:
--  MINUEND: TIMESTAMP - DATE SUBTRACTED FROM
--  SUBTRAHEND: TIMESTAMP - DATE SUBTRACTED
--  INPUT_PART: VARCHAR - PARTS TO BE RETURNED
--  EXTRACT_PART - EXACT NUMERIC VALUE EXTRACTED FROM THE INTERVAL
-- RETURN: NUMBER OF REQUEST PART OF EXTRACT
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.EXTRACT_TIMESTAMP_DIFFERENCE_UDF
(MINUEND TIMESTAMP, SUBTRAHEND TIMESTAMP, INPUT_PART VARCHAR, EXTRACT_PART VARCHAR)
RETURNS INTEGER
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    CASE WHEN INPUT_PART LIKE 'YEAR%' THEN
        CASE WHEN EXTRACT_PART = 'YEAR' THEN
            split(PUBLIC.TIMESTAMP_DIFFERENCE_UDF(MINUEND, SUBTRAHEND, INPUT_PART), '-')[0]::INTEGER
        WHEN EXTRACT_PART = 'MONTH' THEN
            split(PUBLIC.TIMESTAMP_DIFFERENCE_UDF(MINUEND, SUBTRAHEND, INPUT_PART), '-')[1]::INTEGER
        ELSE
            DECODE(EXTRACT_PART,
                    'YEAR',             DATEDIFF(YEAR, SUBTRAHEND, MINUEND),
                    'MONTH',            DATEDIFF(MONTH, SUBTRAHEND, MINUEND),
                    'DAY',              DATEDIFF(DAY, SUBTRAHEND, MINUEND),
                    'HOUR',             DATEDIFF(HOUR, SUBTRAHEND, MINUEND),
                    'MINUTE',           DATEDIFF(MINUTE, SUBTRAHEND, MINUEND),
                    'SECOND',           DATEDIFF(SECOND, SUBTRAHEND, MINUEND)
                    )
        END
    WHEN INPUT_PART LIKE 'DAY%' THEN
        CASE WHEN EXTRACT_PART = 'DAY' THEN
                split(PUBLIC.TIMESTAMP_DIFFERENCE_UDF(MINUEND, SUBTRAHEND, INPUT_PART), ' ')[0]::INTEGER
             WHEN EXTRACT_PART = 'HOUR' THEN
                split(split(PUBLIC.TIMESTAMP_DIFFERENCE_UDF(MINUEND, SUBTRAHEND, INPUT_PART), ' ')[1]::VARCHAR,':')[0]::INTEGER
             WHEN EXTRACT_PART = 'MINUTE' THEN
                split(split(PUBLIC.TIMESTAMP_DIFFERENCE_UDF(MINUEND, SUBTRAHEND, INPUT_PART), ' ')[1]::VARCHAR,':')[1]::INTEGER
             WHEN EXTRACT_PART = 'SECOND' THEN
                split(split(PUBLIC.TIMESTAMP_DIFFERENCE_UDF(MINUEND, SUBTRAHEND, INPUT_PART), ' ')[1]::VARCHAR,':')[2]::INTEGER
        END
    ELSE
        CASE WHEN EXTRACT_PART = 'HOUR' THEN
            split(PUBLIC.TIMESTAMP_DIFFERENCE_UDF(MINUEND, SUBTRAHEND, INPUT_PART),':')[0]::INTEGER
        WHEN EXTRACT_PART = 'MINUTE' THEN
            split(PUBLIC.TIMESTAMP_DIFFERENCE_UDF(MINUEND, SUBTRAHEND, INPUT_PART),':')[1]::INTEGER
        WHEN EXTRACT_PART = 'SECOND' THEN
            split(PUBLIC.TIMESTAMP_DIFFERENCE_UDF(MINUEND, SUBTRAHEND, INPUT_PART),':')[2]::INTEGER
        END
    END
$$;

-- =============================================
-- DISCLAIMER: THIS UDF IS DEPRECATED SINCE AN EQUIVALENT FOR THIS FUNCTION ALREADY EXISTS IN SNOWFLAKE
--  CHECK THE FOLLOWING LINK FOR FURTHER INFORMATION: https://docs.snowflake.com/en/sql-reference/functions/timediff.html
-- DESCRIPTION: UDF THAT GETS DIFFERENCE BETWEEN TWO TIMES 
-- PARAMETERS:
--  MINUEND: TIME - TIME SUBTRACTED FROM
--  SUBTRAHEND: TIME - TIME SUBTRACTED
--  INPUT_PART VARCHAR - RETURN DATA UNTIL PART
-- RETURN: VARCHAR WITH TIME
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.TIME_DIFFERENCE_UDF
(MINUEND TIME, SUBTRAHEND TIME, INPUT_PART VARCHAR)
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
DECODE(INPUT_PART,
        'HOUR',   CASE WHEN HOUR(MINUEND) <= HOUR(SUBTRAHEND) 
                    THEN TO_VARCHAR( HOUR(SUBTRAHEND) - HOUR(MINUEND)           , 'FM9900')
                    ELSE TO_VARCHAR( 24-ABS(HOUR(MINUEND) - HOUR(SUBTRAHEND))   , 'FM9900') END,
        'MINUTE', CASE WHEN HOUR(MINUEND) < HOUR(SUBTRAHEND) 
                    THEN TO_VARCHAR( CASE  WHEN  MINUTE(MINUEND)>MINUTE(SUBTRAHEND)  THEN  (HOUR(SUBTRAHEND) - HOUR(MINUEND)) - 1             ELSE  HOUR(SUBTRAHEND) - HOUR(MINUEND)            END, 'FM9900')
                    ELSE TO_VARCHAR( CASE  WHEN  MINUTE(MINUEND)>MINUTE(SUBTRAHEND)  THEN  (24-ABS(HOUR(MINUEND) - HOUR(SUBTRAHEND))) - 1     ELSE  24-ABS(HOUR(MINUEND) - HOUR(SUBTRAHEND))    END, 'FM9900')
                    END  || ':' ||
                  CASE WHEN MINUTE(MINUEND) <= MINUTE(SUBTRAHEND)
                    THEN TO_VARCHAR( MINUTE(SUBTRAHEND) - MINUTE(MINUEND)          , 'FM9900')
                    ELSE TO_VARCHAR( 60 - ABS(MINUTE(MINUEND) - MINUTE(SUBTRAHEND)), 'FM9900') END,
        'SECOND', CASE WHEN HOUR(MINUEND) <= HOUR(SUBTRAHEND)
                    THEN TO_VARCHAR( CASE WHEN MINUTE(MINUEND) > MINUTE(SUBTRAHEND)  THEN  (HOUR(SUBTRAHEND) - HOUR(MINUEND)) - 1             ELSE  HOUR(SUBTRAHEND) - HOUR(MINUEND)            END, 'FM9900')
                    ELSE TO_VARCHAR( CASE WHEN MINUTE(MINUEND) > MINUTE(SUBTRAHEND)  THEN  (24-ABS(HOUR(MINUEND) - HOUR(SUBTRAHEND))) - 1     ELSE  24-ABS(HOUR(MINUEND) - HOUR(SUBTRAHEND))    END, 'FM9900')
                    END || ':' ||
                  CASE WHEN MINUTE(MINUEND) <= MINUTE(SUBTRAHEND) 
                    THEN TO_VARCHAR( CASE WHEN SECOND(MINUEND) > SECOND(SUBTRAHEND)  THEN  (MINUTE(SUBTRAHEND) - MINUTE(MINUEND)) - 1         ELSE  MINUTE(SUBTRAHEND) - MINUTE(MINUEND)        END, 'FM9900')
                    ELSE TO_VARCHAR( CASE WHEN SECOND(MINUEND) > SECOND(SUBTRAHEND)  THEN  (60 - (MINUTE(MINUEND) - MINUTE(SUBTRAHEND))) - 1  ELSE  60 - (MINUTE(MINUEND) - MINUTE(SUBTRAHEND)) END, 'FM9900')
                    END || ':' ||
                  CASE WHEN SECOND(MINUEND) <= SECOND(SUBTRAHEND)
                    THEN TO_VARCHAR( SECOND(SUBTRAHEND) - SECOND(MINUEND),         'FM9900')
                    ELSE TO_VARCHAR( 60 - (SECOND(MINUEND) - SECOND(SUBTRAHEND)),  'FM9900')
                    END
      )
$$;