-- <copyright file="DATE_TO_NUMERIC_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

-- =============================================
-- DESCRIPTION: UDF THAT REPRODUCES TERADATA'S DATE-TO-NUMERIC FUNCTIONALITY
-- EQUIVALENT: TERADATA'S DATE-TO-NUMERIC FUNCTIONALITY
-- PARAMETERS:
--  DATE_TO_CONVERT: DATE
-- RETURNS: INPUT DATE CONVERTED INTO NUMERIC DATATYPE 
-- EXAMPLE:
--  SELECT DATE_TO_INT_UDF('2022-02-14');
--  RETURNS 1220214
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.DATE_TO_INT_UDF(DATE_TO_CONVERT DATE)
RETURNS INT
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
SELECT  (EXTRACT(YEAR FROM DATE_TO_CONVERT) - 1900) * 10000 + (EXTRACT(MONTH FROM DATE_TO_CONVERT) * 100) + (EXTRACT(DAY FROM DATE_TO_CONVERT))
$$;

-- =============================================
-- DESCRIPTION: UDF THAT REPRODUCES TERADATA'S NUMERIC-TO-DATE FUNCTIONALITY
-- EQUIVALENT: TERADATA'S NUMERIC-TO-DATE FUNCTIONALITY
-- PARAMETERS:
-- NUMERIC_EXPRESSION: INTEGER - NUMBER TO CONVERT
-- RETURNS: INPUT NUMBER CONVERTED INTO DATE DATATYPE 
-- EXAMPLE:
--  SELECT INT_TO_DATE_UDF(1220214);
--  RETURNS '2022-02-14'
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.INT_TO_DATE_UDF(NUMERIC_EXPRESSION INTEGER)
RETURNS DATE
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
TO_DATE(CAST(NUMERIC_EXPRESSION+19000000 AS CHAR(8)), 'YYYYMMDD')
$$;
