-- <copyright file="DAYNUMBER_OF_YEAR_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

-- ======================================================================
-- RETURNS THE DAY OF THE YEAR A TIMESTAMP BELONGS TO, 
-- HAS THE SAME BEHAVIOR AS THE DAYNUMBER_OF_YEAR(DATE, 'ISO') FUNCTION
-- WITH ISO CALENDAR FROM TERADATA
-- PARAMETERS:
--      INPUT: TIMESTAMP_TZ. DATE TO GET THE DAY OF WEEK FROM
-- RETURNS:
--      AN INTEGER BETWEEN 1 AND 371 
--
-- EXAMPLE:
--  SELECT PUBLIC.DAYNUMBER_OF_YEAR_UDF(DATE '2023-01-01'),
--  PUBLIC.DAYNUMBER_OF_YEAR_UDF(DATE '2027-01-03');
-- RETURNS 364, 371
--
-- EQUIVALENT: TERADATA'S DAYNUMBER_OF_YEAR FUNCTIONALITY
-- EXAMPLE:
--  SELECT DAYNUMBER_OF_YEAR (DATE '2023-01-01', 'ISO'),
--  DAYNUMBER_OF_YEAR (DATE '2027-01-03', 'ISO');
-- RETURNS 364, 371
-- ======================================================================
CREATE OR REPLACE FUNCTION PUBLIC.DAYNUMBER_OF_YEAR_UDF(INPUT TIMESTAMP_TZ)
RETURNS INT
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
(WEEKISO(INPUT) - 1) * 7 + DAYOFWEEKISO(INPUT)
$$;