-- <copyright file="DAYNUMBER_OF_MONTH_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

CREATE OR REPLACE FUNCTION PUBLIC.FIRST_DAY_OF_MONTH_ISO_UDF(YEAR NUMBER, MONTH NUMBER)
RETURNS DATE 
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    DATE_FROM_PARTS(
        YEAR,
        MONTH,
        (iff(dayofweek(date_from_parts(YEAR,MONTH,1)) <= 4, 0 ,7) - dayofweek(date_from_parts(YEAR,MONTH,1))) + 2
    )
$$;

-- ======================================================================
-- RETURNS THE DAY OF THE MONTH A TIMESTAMP BELONGS TO, 
-- HAS THE SAME BEHAVIOR AS THE DAYNUMBER_OF_MONTH(DATE, 'ISO') FUNCTION
-- WITH ISO CALENDAR FROM TERADATA
-- PARAMETERS:
--      INPUT: TIMESTAMP_TZ. DATE TO GET THE DAY OF WEEK FROM
-- RETURNS:
--      AN INTEGER BETWEEN 1 AND 33
--
-- EXAMPLE:
--  SELECT PUBLIC.DAYNUMBER_OF_MONTH_UDF(DATE '2023-01-01'),
--  PUBLIC.DAYNUMBER_OF_MONTH_UDF(DATE '2027-01-03');
-- RETURNS 28, 26
--
-- EQUIVALENT: TERADATA'S DAYNUMBER_OF_MONTH FUNCTIONALITY
-- EXAMPLE:
--  SELECT DAYNUMBER_OF_MONTH(DATE '2023-01-01', 'ISO'),
--  DAYNUMBER_OF_MONTH(DATE '2027-01-03', 'ISO');
-- RETURNS 28, 26
-- ======================================================================
CREATE OR REPLACE FUNCTION PUBLIC.DAYNUMBER_OF_MONTH_UDF(INPUT TIMESTAMP_TZ)
RETURNS NUMBER 
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    DATEDIFF(
        DAY,
        CASE
            WHEN INPUT::DATE >= PUBLIC.FIRST_DAY_OF_MONTH_ISO_UDF(YEAR(INPUT), MONTH(INPUT)+1) THEN PUBLIC.FIRST_DAY_OF_MONTH_ISO_UDF(YEAR(INPUT), MONTH(INPUT)+1)
            WHEN INPUT::DATE >= PUBLIC.FIRST_DAY_OF_MONTH_ISO_UDF(YEAR(INPUT), MONTH(INPUT)) THEN PUBLIC.FIRST_DAY_OF_MONTH_ISO_UDF(YEAR(INPUT), MONTH(INPUT))
            ELSE PUBLIC.FIRST_DAY_OF_MONTH_ISO_UDF(YEAR(INPUT), MONTH(INPUT)-1)
        END,
        INPUT
    ) + 1
$$;