-- <copyright file="EXPAND_ON_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>


-- ======================================================================
-- DESCRIPTION: CALCULATES THE EXPAND ON DEPENDING ON THE PERIODTYPE ARGUMENT
-- PARAMETERS:
--      TIME:   STRING. EXPAND ON TIME USE IN ANCHOR.
--      SEQ:    NUMBER. THE SEQUENCE TO CALCULATE EACH ROW.
--      PERIOD: TIMESTAMP. THE DATE FROM PERIOD NEEDED
--      PERIODTYPE: STRING. THE PERIOD TYPE FOR THE CALCULATION (BEGIN/END)
-- RETURNS:
--      A TIMESTAMP THAT REPRESENTS EACH ROW OF THE EXPAND ON
--
-- EXAMPLE:
-- SELECT id,PUBLIC.COMPUTE_EXPAND_ON_UDF('ANCHOR_SECOND', value, PERIOD_BEGIN_UDF(pd), 'BEGIN') from PUBLIC.tdate,
-- table(flatten(PUBLIC.ROW_COUNT_UDF(PUBLIC.DIFF_TIME_PERIOD_UDF('SECONDS',pd))));
-- 1 2021-01-01 11:34:21
-- 2 2021-01-01 11:34:22
-- 3 2021-01-01 11:34:23
-- ======================================================================
CREATE OR REPLACE FUNCTION PUBLIC.COMPUTE_EXPAND_ON_UDF(TIME STRING, SEQ NUMBER, PERIOD TIMESTAMP, PERIODTYPE STRING)
RETURNS TIMESTAMP
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
CASE
WHEN TIME='ANCHOR_MILLISECOND' THEN
 IFF(PERIODTYPE = 'BEGIN',
       DATEADD(MILLISECOND,SEQ,PERIOD),
       DATEADD(MILLISECOND,SEQ+1,PERIOD))
WHEN TIME='ANCHOR_SECOND' THEN
 IFF(PERIODTYPE = 'BEGIN',
       DATEADD(SECOND,SEQ,TIMESTAMP_FROM_PARTS( YEAR(PERIOD),MONTH(PERIOD),DAY(PERIOD), HOUR(PERIOD),MINUTE(PERIOD),SECOND(PERIOD))),
       DATEADD(SECOND,SEQ+1,TIMESTAMP_FROM_PARTS( YEAR(PERIOD),MONTH(PERIOD),DAY(PERIOD), HOUR(PERIOD),MINUTE(PERIOD),SECOND(PERIOD))))
WHEN TIME= 'ANCHOR_MINUTE' THEN
 IFF(PERIODTYPE = 'BEGIN',
       DATEADD(MINUTE,SEQ,TIMESTAMP_FROM_PARTS( YEAR(PERIOD),MONTH(PERIOD),DAY(PERIOD), HOUR(PERIOD),MINUTE(PERIOD),0)),
       DATEADD(MINUTE,SEQ+1,TIMESTAMP_FROM_PARTS( YEAR(PERIOD),MONTH(PERIOD),DAY(PERIOD), HOUR(PERIOD),MINUTE(PERIOD),0)))
WHEN TIME= 'ANCHOR_HOUR' THEN
 IFF(PERIODTYPE = 'BEGIN',
       DATEADD(HOUR,SEQ,TIMESTAMP_FROM_PARTS( YEAR(PERIOD),MONTH(PERIOD),DAY(PERIOD),  HOUR(PERIOD),0,0)),
       DATEADD(HOUR,SEQ+1,TIMESTAMP_FROM_PARTS( YEAR(PERIOD),MONTH(PERIOD),DAY(PERIOD),  HOUR(PERIOD),0,0)))
WHEN TIME= 'WEEK_BEGIN' THEN
 IFF(PERIODTYPE = 'BEGIN',
       TIMESTAMP_FROM_PARTS(LAST_DAY(DATEADD(day,SEQ*7,PERIOD), WEEK)-7,to_time('00:00:00.000')),
       TIMESTAMP_FROM_PARTS(LAST_DAY(DATEADD(day,(SEQ+1)*7,PERIOD), WEEK)-7,to_time('00:00:00.000')))
WHEN TIME= 'WEEK_END' THEN
 IFF(PERIODTYPE = 'BEGIN',
       TIMESTAMP_FROM_PARTS(LAST_DAY(DATEADD(day,SEQ*7,PERIOD), WEEK)-8,to_time('23:59:59.999')),
       TIMESTAMP_FROM_PARTS(LAST_DAY(DATEADD(day,(SEQ+1)*7,PERIOD), WEEK)-8,to_time('23:59:59.999')))
WHEN TIME= 'MONTH_BEGIN' THEN
 IFF(PERIODTYPE = 'BEGIN',
       DATEADD(month,SEQ,TIMESTAMP_FROM_PARTS( YEAR(PERIOD),MONTH(PERIOD),1,0,0,0)),
       DATEADD(month,SEQ+1,TIMESTAMP_FROM_PARTS( YEAR(PERIOD),MONTH(PERIOD),1,0,0,0)))
WHEN TIME= 'MONTH_END' THEN
 IFF(PERIODTYPE = 'BEGIN',
       TIMESTAMP_FROM_PARTS(LAST_DAY(DATEADD(month,SEQ-1,PERIOD)),to_time('23:59:59.999')),
       TIMESTAMP_FROM_PARTS(LAST_DAY(DATEADD(month,SEQ,PERIOD)),to_time('23:59:59.999')))
WHEN TIME= 'QUARTER_BEGIN' THEN
 IFF(PERIODTYPE = 'BEGIN',
       date_trunc('QUARTER', DATEADD(QUARTER,SEQ,PERIOD)),
       date_trunc('QUARTER', DATEADD(QUARTER,SEQ+1,PERIOD)))
WHEN TIME= 'QUARTER_END' THEN
 IFF(PERIODTYPE = 'BEGIN', 
       TIMESTAMP_FROM_PARTS(LAST_DAY(DATEADD(QUARTER,SEQ-1,PERIOD), QUARTER),to_time('23:59:59.999')),
       TIMESTAMP_FROM_PARTS(LAST_DAY(DATEADD(QUARTER,SEQ,PERIOD), QUARTER),to_time('23:59:59.999')))
WHEN TIME= 'YEAR_BEGIN' THEN
 IFF(PERIODTYPE = 'BEGIN',
       date_trunc('YEAR', DATEADD(YEAR,SEQ,PERIOD)),
       date_trunc('YEAR', DATEADD(YEAR,SEQ+1,PERIOD)))
WHEN TIME= 'YEAR_END' THEN
 IFF(PERIODTYPE = 'BEGIN',
       TIMESTAMP_FROM_PARTS(LAST_DAY(DATEADD(YEAR,SEQ-1,PERIOD), YEAR),to_time('23:59:59.999')),
       TIMESTAMP_FROM_PARTS(LAST_DAY(DATEADD(YEAR,SEQ,PERIOD), YEAR),to_time('23:59:59.999')) ) 
END
$$;

-- ======================================================================
-- DESCRIPTION: REPRODUCES TERADATA'S EXPAND ON FUNCTIONALITY
-- PARAMETERS:
--      TIME:   STRING. EXPAND ON TIME USE IN ANCHOR.
--      SEQ:    NUMBER. THE SEQUENCE TO CALCULATE EACH ROW.
--      PERIOD: PERIOD. THE DATE FROM PERIOD NEEDED
-- RETURNS:
--      A VARCHAR THAT REPRESENTS THE CALCULATION OF THE EXPAND ON CLAUSE FOR PERIOD
--
-- EXAMPLE:
-- SELECT id,PUBLIC.EXPAND_ON('ANCHOR_SECOND', value, PERIOD_BEGIN_UDF(pd)) from PUBLIC.tdate, 
-- table(flatten(PUBLIC.ROW_COUNT_UDF(PUBLIC.DIFF_TIME_PERIOD_UDF('SECONDS',pd))));
-- 1 2021-01-01 11:34:21*2021-01-01 11:34:22
-- 2 2021-01-01 11:34:22*2021-01-01 11:34:23
-- 3 2021-01-01 11:34:23*2021-01-01 11:34:24
--
-- EQUIVALENT: TERADATA'S EXPAND ON FUNCTIONALITY
-- EXAMPLE:
-- SELECT bg
-- FROM tdate
-- EXPAND ON pd AS bg BY ANCHOR ANCHOR_SECOND;
-- RETURNS :
-- 1 (2021-01-01 11:34:21,2021-01-01 11:34:22)
-- 2 (2021-01-01 11:34:22,2021-01-01 11:34:23)
-- 3 (2021-01-01 11:34:23,2021-01-01 11:34:24)
-- ======================================================================
CREATE OR REPLACE FUNCTION PUBLIC.EXPAND_ON_UDF(TIME STRING, SEQ NUMBER, PERIOD STRING)
RETURNS VARCHAR(50)
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
PUBLIC.PERIOD_UDF(COMPUTE_EXPAND_ON_UDF(TIME, SEQ, PUBLIC.PERIOD_BEGIN_UDF(PERIOD),'BEGIN'), COMPUTE_EXPAND_ON(TIME,SEQ,  PUBLIC.PERIOD_BEGIN_UDF(PERIOD),'END'))
$$;

-- ======================================================================
-- DESCRIPTION: CALCULATES THE DIFFERENCE BETWEEN TWO DATES DEPENDING ON TIME PARAMETER
-- PARAMETERS:
--      TIME:   STRING. EXPAND ON TIME USE IN ANCHOR..
--      PERIOD: PERIOD. PERIOD COLUMN USE IN THE EXPAND ON
-- RETURNS:
--      A NUMBER THAT REPRESENTS THE DIFFERENCE BETWEEN TWO DATES
--
-- EXAMPLE:
-- SELECT DIFF_TIME_PERIOD_UDF('SECONDS','2022-11-26 10:15:20.000*2022-11-26 10:15:25.000');
-- RETURNS : 5
-- ======================================================================
CREATE OR REPLACE FUNCTION PUBLIC.DIFF_TIME_PERIOD_UDF(TIME STRING,PERIOD varchar(50))
RETURNS NUMBER
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
CASE 
WHEN TIME = 'ANCHOR_MILLISECOND' THEN
DATEDIFF(MILLISECOND, PUBLIC.PERIOD_BEGIN_UDF(PERIOD), PUBLIC.PERIOD_END_UDF(PERIOD))
WHEN TIME = 'ANCHOR_SECOND' THEN
DATEDIFF(SECOND, PUBLIC.PERIOD_BEGIN_UDF(PERIOD), PUBLIC.PERIOD_END_UDF(PERIOD))
WHEN TIME = 'ANCHOR_MINUTE' THEN 
DATEDIFF(MINUTE, PUBLIC.PERIOD_BEGIN_UDF(PERIOD), PUBLIC.PERIOD_END_UDF(PERIOD))
WHEN TIME = 'ANCHOR_HOUR' THEN 
DATEDIFF(HOUR, PUBLIC.PERIOD_BEGIN_UDF(PERIOD), PUBLIC.PERIOD_END_UDF(PERIOD))
WHEN TIME = 'WEEK_BEGIN' OR TIME ='WEEK_END' THEN 
DATEDIFF(WEEK, PUBLIC.PERIOD_BEGIN_UDF(PERIOD), PUBLIC.PERIOD_END_UDF(PERIOD))
WHEN TIME = 'MONTH_BEGIN' OR TIME ='MONTH_END' THEN 
DATEDIFF(MONTH, PUBLIC.PERIOD_BEGIN_UDF(PERIOD), PUBLIC.PERIOD_END_UDF(PERIOD))
WHEN TIME = 'QUARTER_BEGIN' OR TIME ='QUARTER_END' THEN 
DATEDIFF(QUARTER, PUBLIC.PERIOD_BEGIN_UDF(PERIOD), PUBLIC.PERIOD_END_UDF(PERIOD))
WHEN TIME = 'YEAR_BEGIN' OR TIME ='YEAR_END' THEN 
DATEDIFF(YEAR, PUBLIC.PERIOD_BEGIN_UDF(PERIOD), PUBLIC.PERIOD_END_UDF(PERIOD))
END
$$;

-- ======================================================================
-- DESCRIPTION: RETURN AN ARRAY FROM 1 TO THE NUMBER RETURN IN DIFF_TIME_PERIOD_UDF
-- PARAMETERS:
--      NROWS:   DOUBLE.  THE NUMBER RETURN IN DIFF_TIME_PERIOD_UDF
-- RETURNS:
--      AN ARRAY TO CALCULATE HOW MANY ROWS ARE NEEDED TO SIMULATE
--      THE EXPAND ON CLAUSE
--
-- EXAMPLE:
--  SELECT ROW_COUNT_UDF(DIFFTTIME_PERIOD('SECONDS','2022-11-26 10:15:20.000*2022-11-26 10:15:25.000'));
-- RETURNS [1, 2, 3, 4, 5]
-- ======================================================================
CREATE OR REPLACE FUNCTION PUBLIC.ROW_COUNT_UDF(NROWS DOUBLE)
RETURNS variant
LANGUAGE JAVASCRIPT
<SnowConvertVersionComment>
  AS '
  
    var returnArray = [];
for (let i = 1; i <= NROWS; i++) {
    returnArray.push(i);
    }

    return returnArray;
  ';