-- <copyright file="MONTHS_BETWEEN_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

-- =============================================
-- DESCRIPTION: UDF THAT REPRODUCES MONTHS_BETWEEN FUNCTIONALITY
-- PARAMETERS: MONTHS_BETWEEN
-- FIRST_DATE: TIMESTAMP_LTZ
-- SECOND_DATE: TIMESTAMP_LTZ
-- RETURNS: NUMBER OF MONTHS BETWEEN FIRST_DATE AND SECOND_DATE
-- EXAMPLE:
--  SELECT MONTHS_BETWEEN_UDF('2022-02-14', '2021-02-14'); -- SELECT MONTHS_BETWEEN(TO_DATE('2022-02-14','YYYY-MM-DD'), TO_DATE('2021-02-14','YYYY-MM-DD')) FROM DUAL;
--  RETURNS 12
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.MONTHS_BETWEEN_UDF(FIRST_DATE TIMESTAMP_LTZ, SECOND_DATE TIMESTAMP_LTZ)
RETURNS NUMBER
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
ROUND(MONTHS_BETWEEN(FIRST_DATE, SECOND_DATE))
$$
;