-- <copyright file="NULLIFZERO_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

-- =============================================
-- DESCRIPTION: CONVERTS DATA FROM ZERO TO NULL TO AVOID PROBLEMS WITH DIVISION BY ZERO.
-- EQUIVALENT: TERADATA'S NULLIFZERO FUNCTIONALITY
-- PARAMETERS:
-- NUMBER_TO_VALIDATE: NUMBER - INPUT NUMBER THAT WILL BE CHECKED.
-- RETURNS: NULL IF THE NUMBER IS ZERO, OTHERWISE THE NUMBER
-- EXAMPLE:
--  1:
--      SELECT NULLIFZERO_UDF(0);
--      RETURNS NULL
--  2:
--      SELECT NULLIFZERO_UDF(10);
--      RETURNS 10
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.NULLIFZERO_UDF(NUMBER_TO_VALIDATE NUMBER)
RETURNS NUMBER
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    DECODE(NUMBER_TO_VALIDATE , 0, NULL, NUMBER_TO_VALIDATE)
$$;
