-- <copyright file="PERIOD_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

-- =============================================
-- DESCRIPTION: GETS THE SEPARATOR USED TO SPLIT THE PERIOD BEGIN/END
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.GET_PERIOD_SEPARATOR()
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
SELECT '*'
$$;
    
-- =============================================
-- DESCRIPTION: EMULATES THE BEHAVIOR OF THE END FUNCTION
-- EQUIVALENT: TERADATA'S END FUNCTION
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_END_UDF(PERIOD_VAL VARCHAR(22))
RETURNS TIMESTAMP
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
 CAST(SUBSTR(PERIOD_VAL,POSITION(PUBLIC.GET_PERIOD_SEPARATOR(),PERIOD_VAL)+1) AS TIMESTAMP)
$$;

-- =============================================
-- DESCRIPTION: EMULATES THE BEHAVIOR OF THE BEGIN FUNCTION
-- EQUIVALENT: TERADATA'S BEGIN FUNCTION
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_BEGIN_UDF(PERIOD_VAL VARCHAR(22))
RETURNS TIMESTAMP
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
 CAST(SUBSTR(PERIOD_VAL,1, POSITION(PUBLIC.GET_PERIOD_SEPARATOR(),PERIOD_VAL)-1) AS TIMESTAMP)
$$;

-- =============================================
-- DESCRIPTION: EMULATES THE BEHAVIOR OF THE LAST FUNCTION
-- EQUIVALENT: TERADATA'S LAST FUNCTION
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_LAST_UDF(PERIOD_VAL VARCHAR(22))
RETURNS TIMESTAMP
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
 CASE 
    WHEN PERIOD_VAL REGEXP '(.)*\\:(.)*' THEN DATEADD(millisecond, -1, CAST(SUBSTR(PERIOD_VAL,POSITION(PUBLIC.GET_PERIOD_SEPARATOR(),PERIOD_VAL)+1) AS TIMESTAMP))
    ELSE CAST(SUBSTR(PERIOD_VAL,POSITION(PUBLIC.GET_PERIOD_SEPARATOR(),PERIOD_VAL)+1) AS TIMESTAMP)
 END
$$;

-- =============================================
-- DESCRIPTION: EMULATES THE BEHAVIOR OF THE OVERLAPS FUNCTION
-- EQUIVALENT: TERADATA'S OVERLAPS FUNCTION
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_OVERLAPS_UDF(PERIOD_1 VARCHAR(22), PERIOD_2 VARCHAR(22))
RETURNS BOOLEAN
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
 CASE WHEN 
    (NOT ((PERIOD_BEGIN_UDF(PERIOD_1) >= PERIOD_END_UDF(PERIOD_2)) OR (PERIOD_BEGIN_UDF(PERIOD_2) >= PERIOD_END_UDF(PERIOD_1))))
THEN
    TRUE
ELSE
    FALSE
END 
$$;

-- =============================================
-- DESCRIPTION: EMULATES THE BEHAVIOR OF THE LDIFF FUNCTION
-- EQUIVALENT: TERADATA'S LDIFF FUNCTION
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_LDIFF_UDF(PERIOD_1 VARCHAR(50), PERIOD_2 VARCHAR(50))
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
 CASE WHEN PUBLIC.PERIOD_OVERLAPS_UDF(PERIOD_2, PERIOD_1) = 'TRUE' 
            AND PUBLIC.PERIOD_BEGIN_UDF(PERIOD_1) < PUBLIC.PERIOD_BEGIN_UDF(PERIOD_2) 
       THEN
        SUBSTR(PERIOD_1,1, POSITION(PUBLIC.GET_PERIOD_SEPARATOR(),PERIOD_1)-1) || PUBLIC.GET_PERIOD_SEPARATOR() || SUBSTR(PERIOD_2,1, POSITION(PUBLIC.GET_PERIOD_SEPARATOR(),PERIOD_2)-1)
       ELSE
         NULL
       END     
$$;

-- =============================================
-- DESCRIPTION: EMULATES THE BEHAVIOR OF THE RDIFF FUNCTION
-- EQUIVALENT: TERADATA'S RDIFF FUNCTION
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_RDIFF_UDF(PERIOD_1 VARCHAR(50), PERIOD_2 VARCHAR(50))
RETURNS VARCHAR
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
CASE WHEN PUBLIC.PERIOD_OVERLAPS_UDF(PERIOD_2, PERIOD_1) = 'TRUE' 
            AND PUBLIC.PERIOD_END_UDF(PERIOD_1) > PUBLIC.PERIOD_END_UDF(PERIOD_2) 
       THEN
        SUBSTR(PERIOD_2,POSITION(PUBLIC.GET_PERIOD_SEPARATOR(),PERIOD_2)+1) || PUBLIC.GET_PERIOD_SEPARATOR() || SUBSTR(PERIOD_1,POSITION(PUBLIC.GET_PERIOD_SEPARATOR(),PERIOD_1)+1)
       ELSE
         NULL
       END
$$;

-- =============================================
-- DESCRIPTION: GENERATES A VARCHAR REPRESENTATION OF THE TWO BOUNDS OF A PERIOD(TIMESTAMP) VALUE, USED TO EMULATE THE TERADATA PERIOD VALUE CONSTRUCTOR FUNCTION.
-- THIS VERSION GENERATES THE RESULTING STRING USING THE DEFAULT FORMAT SNOWFLAKE HAS FOR REPRESENTING TIMESTAMP VALUES, IF YOU REQUIRE LESS OR MORE PRECISION
-- EITHER CHANGE THE SESSION PARAMETER TIMESTAMP_OUTPUT_FORMAT OR USE THE THREE PARAMETERS VERSION OF THIS UDF 
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_UDF(D1 TIMESTAMP_NTZ, D2 TIMESTAMP_NTZ)
RETURNS STRING
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
TO_VARCHAR(D1) || PUBLIC.GET_PERIOD_SEPARATOR() || TO_VARCHAR(D2)
$$;

-- =============================================
-- DESCRIPTION: GENERATES A VARCHAR REPRESENTATION OF THE TWO BOUNDS OF A PERIOD(DATE) VALUE, USED TO EMULATE THE TERADATA PERIOD VALUE CONSTRUCTOR FUNCTION.
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_UDF(D1 DATE, D2 DATE)
RETURNS STRING
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
TO_VARCHAR(D1) || PUBLIC.GET_PERIOD_SEPARATOR() || TO_VARCHAR(D2)
$$;

-- =============================================
-- Description: Generates a varchar representation of the two bounds of a period(time) value, used to emulate the Teradata Period Value Constructor Function.
-- This version generates the resulting string using the default format Snowflake has for representing timestamp values, if you require less or more precision
-- either change the session parameter TIME_OUTPUT_FORMAT or use the three parameters version of this UDF 
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_UDF(D1 TIME, D2 TIME)
RETURNS STRING
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
TO_VARCHAR(D1) || PUBLIC.GET_PERIOD_SEPARATOR() || TO_VARCHAR(D2)
$$;

-- =============================================
-- DESCRIPTION: GENERATES A VARCHAR REPRESENTATION OF THE TWO BOUNDS OF A PERIOD(TIMESTAMP) VALUE, THIS VERSION ALLOWS TO DEFINE HOW MANY PRECISION DIGITS ARE
-- DESIRED IN THE RESULT (UP TO 9, HOWEVER, PLEASE KEEP IN MIND TERADATA MAXIMUM PRECISION FOR TIMESTAMPS IS 6)
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_UDF(D1 TIMESTAMP_NTZ, D2 TIMESTAMP_NTZ, PRECISIONDIGITS INT)
RETURNS STRING
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
CASE WHEN PRECISIONDIGITS <= 0 THEN
        TO_VARCHAR(D1, 'YYYY-MM-DD HH24:MI:SS') || PUBLIC.GET_PERIOD_SEPARATOR() || TO_VARCHAR(D2, 'YYYY-MM-DD HH24:MI:SS')
     WHEN PRECISIONDIGITS > 9 THEN
        TO_VARCHAR(D1, 'YYYY-MM-DD HH24:MI:SS.FF9') || PUBLIC.GET_PERIOD_SEPARATOR() || TO_VARCHAR(D2, 'YYYY-MM-DD HH24:MI:SS.FF9')
     ELSE
        TO_VARCHAR(D1, 'YYYY-MM-DD HH24:MI:SS.FF' || PRECISIONDIGITS) || PUBLIC.GET_PERIOD_SEPARATOR() || TO_VARCHAR(D2, 'YYYY-MM-DD HH24:MI:SS.FF' || PRECISIONDIGITS)
END
$$;

-- =============================================
-- DESCRIPTION: GENERATES A VARCHAR REPRESENTATION OF THE TWO BOUNDS OF A PERIOD(TIME) VALUE, THIS VERSION ALLOWS TO DEFINE HOW MANY PRECISION DIGITS ARE
-- DESIRED IN THE RESULT (UP TO 9, HOWEVER, PLEASE KEEP IN MIND TERADATA MAXIMUM PRECISION FOR TIME IS 6)
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_UDF(D1 TIME, D2 TIME, PRECISIONDIGITS INT)
RETURNS STRING
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
CASE WHEN PRECISIONDIGITS <= 0 THEN
        TO_VARCHAR(D1, 'HH24:MI:SS') || PUBLIC.GET_PERIOD_SEPARATOR() || TO_VARCHAR(D2, 'HH24:MI:SS')
     WHEN PRECISIONDIGITS > 9 THEN
        TO_VARCHAR(D1, 'HH24:MI:SS.FF9') || PUBLIC.GET_PERIOD_SEPARATOR() || TO_VARCHAR(D2, 'HH24:MI:SS.FF9')
     ELSE
        TO_VARCHAR(D1, 'HH24:MI:SS.FF' || PRECISIONDIGITS) || PUBLIC.GET_PERIOD_SEPARATOR() || TO_VARCHAR(D2, 'HH24:MI:SS.FF' || PRECISIONDIGITS)
END
$$;

-- =============================================
-- DESCRIPTION: EMULATES THE TERADATA PERIOD VALUE CONSTRUCTOR FUNCTION OVERLOAD WITH A SINGLE TIMESTAMP PARAMETER, IN THE ORIGINAL BEHAVIOR TERADATA ADDS ONE
-- TO THE SMALLEST TIME PART OF THE TIMESTAMP (UP TO MICROSECONDS AT PRECISION 6) BUT SNOWFLAKE TIMESTAMPS DEFAULT TO PRECISION 9 (NANOSECONDS), A MICROSECOND IS
-- ADDED TO MATCH TERADATA'S MAXIMUM PRECISION FOR TIMESTAMPS SO RESULTS MIGHT DIFFER AT LOWER PRECISIONS
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_UDF(D1 TIMESTAMP_NTZ)
RETURNS STRING
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
TO_VARCHAR(D1) || PUBLIC.GET_PERIOD_SEPARATOR() || TO_VARCHAR(DATEADD(MICROSECOND, 1, D1))
$$;

-- =============================================
-- DESCRIPTION: EMULATES THE TERADATA PERIOD VALUE CONSTRUCTOR FUNCTION OVERLOAD WITH A SINGLE DATE PARAMETER
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_UDF(D1 DATE)
RETURNS STRING
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
TO_VARCHAR(D1) || PUBLIC.GET_PERIOD_SEPARATOR() || TO_VARCHAR(DATEADD(DAY, 1, D1))
$$;

-- =============================================
-- DESCRIPTION: EMULATES THE TERADATA PERIOD VALUE CONSTRUCTOR FUNCTION OVERLOAD WITH A SINGLE TIME PARAMETER, IN THE ORIGINAL BEHAVIOR TERADATA ADDS ONE
-- TO THE SMALLEST TIME PART OF THE TIME TYPE (UP TO MICROSECONDS AT PRECISION 6) BUT SNOWFLAKE TIME TYPE DEFAULTS TO PRECISION 9 (NANOSECONDS), A MICROSECOND IS
-- ADDED TO MATCH TERADATA'S MAXIMUM PRECISION FOR TIME SO RESULTS MIGHT DIFFER AT LOWER PRECISIONS
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_UDF(D1 TIME)
RETURNS STRING
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
TO_VARCHAR(D1, 'YYYY-MM-DD HH24:MI:SS.FF6') || PUBLIC.GET_PERIOD_SEPARATOR() || TO_VARCHAR(DATEADD(MICROSECOND, 1, D1), 'YYYY-MM-DD HH24:MI:SS.FF6')
$$;

-- =============================================
-- DESCRIPTION: EMULATES PERIOD TO TIME CASTING BEHAVIOR
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_TO_TIME_UDF(PERIOD_VAL VARCHAR(22))
RETURNS TIME
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
TO_TIME(TO_TIMESTAMP((SUBSTR(PERIOD_VAL,1, POSITION(PUBLIC.GET_PERIOD_SEPARATOR(),PERIOD_VAL)-1))))
$$;

-- =============================================
-- DESCRIPTION: EMULATES PERIOD CONTAINS BEHAVIOR
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_CONTAINS_UDF(PERIOD_VAL VARCHAR, TS TIMESTAMP_NTZ)
RETURNS BOOLEAN
IMMUTABLE
<SnowConvertVersionComment>
AS
$$ 
TS BETWEEN PUBLIC.PERIOD_BEGIN_UDF(PERIOD_VAL) AND PUBLIC.PERIOD_END_UDF(PERIOD_VAL) 
$$;
       
-- =============================================
-- DESCRIPTION: EMULATES PERIOD CONTAINS BEHAVIOR
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_CONTAINS_UDF(PERIOD_VAL VARCHAR, DATE_VAL DATE)
RETURNS BOOLEAN
IMMUTABLE
<SnowConvertVersionComment>
AS
$$ 
DATE_VAL BETWEEN CAST(SUBSTR(PERIOD_VAL,1, POSITION(PUBLIC.GET_PERIOD_SEPARATOR(),PERIOD_VAL)-1) AS DATE) AND CAST(SUBSTR(PERIOD_VAL,POSITION(PUBLIC.GET_PERIOD_SEPARATOR(),PERIOD_VAL)+1) AS DATE)
$$;
       
-- =============================================
-- DESCRIPTION: EMULATES PERIOD CONTAINS BEHAVIOR
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_CONTAINS_UDF(PERIOD_VAL VARCHAR, TIME_VAL TIME)
RETURNS BOOLEAN
IMMUTABLE
<SnowConvertVersionComment>
AS
$$ 
TIME_VAL BETWEEN CAST(SUBSTR(PERIOD_VAL,1, POSITION(PUBLIC.GET_PERIOD_SEPARATOR(), PERIOD_VAL)-1) AS TIME) AND CAST(SUBSTR(PERIOD_VAL,POSITION(PUBLIC.GET_PERIOD_SEPARATOR(), PERIOD_VAL)+1) AS TIME)
$$;
       
       
-- =============================================
-- DESCRIPTION: EMULATES PERIOD CONTAINS BEHAVIOR
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.PERIOD_CONTAINS_UDF(PERIOD_VAL VARCHAR, PERIOD_VAL_2 VARCHAR)
RETURNS BOOLEAN
IMMUTABLE
<SnowConvertVersionComment>
AS
$$ 
WITH CTE AS 
(
  SELECT SUBSTR(PERIOD_VAL_2, 1, POSITION(PUBLIC.GET_PERIOD_SEPARATOR(), PERIOD_VAL_2) - 1) AS PERIOD_BEGIN, SUBSTR(PERIOD_VAL_2, POSITION(PUBLIC.GET_PERIOD_SEPARATOR(), PERIOD_VAL_2) + 1) AS PERIOD_END
)
SELECT CASE
           WHEN TRY_TO_TIME(PERIOD_BEGIN) IS NOT NULL AND TRY_TO_TIME(PERIOD_END) IS NOT NULL THEN PERIOD_CONTAINS_UDF(PERIOD_VAL, TO_TIME(PERIOD_BEGIN)) AND PERIOD_CONTAINS_UDF(PERIOD_VAL, TO_TIME(PERIOD_END))
           WHEN TRY_TO_TIMESTAMP(PERIOD_BEGIN) IS NOT NULL AND TRY_TO_TIMESTAMP(PERIOD_END) IS NOT NULL THEN PERIOD_CONTAINS_UDF(PERIOD_VAL, TO_TIMESTAMP(PERIOD_BEGIN)) AND PERIOD_CONTAINS_UDF(PERIOD_VAL, TO_TIMESTAMP(PERIOD_END))
           WHEN TRY_TO_DATE(PERIOD_BEGIN) IS NOT NULL AND TRY_TO_DATE(PERIOD_END) IS NOT NULL THEN PERIOD_CONTAINS_UDF(PERIOD_VAL, TO_DATE(PERIOD_BEGIN)) AND PERIOD_CONTAINS_UDF(PERIOD_VAL, TO_DATE(PERIOD_END))
           ELSE FALSE
        END
FROM CTE
$$;