-- <copyright file="QUARTERNUMBER_OF_YEAR_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

-- ======================================================================
-- DESCRIPTION: UDF THAT REPRODUCES TERADATA'S QUARTERNUMBER_OF_YEAR(Date,'ISO') FUNCTIONALITY
-- PARAMETERS:
--      INPUT: TIMESTAMP_TZ. DATE TO GET THE NUMBER OF QUARTER FROM
-- RETURNS:
--      AN INTEGER THAT REPRESENTS THE QUARTER THE DATE BELONGS TO
--
-- EXAMPLE:
--  SELECT PUBLIC.QUARTERNUMBER_OF_YEAR_UDF(DATE '2022-01-01'),
--  PUBLIC.QUARTERNUMBER_OF_YEAR_UDF(DATE '2025-12-31');
-- RETURNS 4, 1
--
-- EQUIVALENT: TERADATA'S QUARTERNUMBER_OF_YEAR FUNCTIONALITY
-- EXAMPLE:
--  SELECT QUARTERNUMBER_OF_YEAR(DATE '2022-01-01', 'ISO'),
--  QUARTERNUMBER_OF_YEAR(DATE '2025-12-31', 'ISO');
-- RETURNS 4, 1
-- ======================================================================
CREATE OR REPLACE FUNCTION PUBLIC.QUARTERNUMBER_OF_YEAR_UDF(INPUT TIMESTAMP_TZ)
RETURNS INT
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    CASE
        WHEN WEEKISO(INPUT)<=13 THEN 1
        WHEN WEEKISO(INPUT)<=26 THEN 2
        WHEN WEEKISO(INPUT)<=39 THEN 3
        ELSE 4
    END
$$;