-- <copyright file="TD_DAY_OF_WEEK_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

-- ======================================================================
-- RETURNS THE DAY OF THE WEEK A TIMESTAMP BELONGS TO, HAS THE SAME BEHAVIOR AS THE TD_DAY_OF WEEK FUNCTION FROM TERADATA
-- PARAMETERS:
--      INPUT: TIMESTAMP_TZ. DATE TO GET THE DAY OF WEEK FROM
-- RETURNS:
--      AN INTEGER BETWEEN 1 AND 7 WHERE 1 = SUNDAY, 2 = MONDAY, ..., 7 = SATURDAY
-- ======================================================================
CREATE OR REPLACE FUNCTION PUBLIC.TD_DAY_OF_WEEK_UDF(INPUT TIMESTAMP_TZ)
RETURNS INT
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    IFF(DAYOFWEEKISO(INPUT) = 7, 1, DAYOFWEEKISO(INPUT) + 1)
$$;

-- ======================================================================
-- RETURNS THE DAY OF THE WEEK A TIMESTAMP BELONGS TO, 
-- HAS THE SAME BEHAVIOR AS THE DAYNUMBER_OF_WEEK(DATE, 'COMPATIBLE') FUNCTION
-- WITH COMPATIBLE CALENDAR FROM TERADATA,FIRST DAY OF THE WEEK WILL BE THE SAME
-- DAY AS THE DAY OF THE FIRST OF JANUARY
-- PARAMETERS:
--      INPUT: TIMESTAMP_TZ. DATE TO GET THE DAY OF WEEK FROM
-- RETURNS:
--      AN INTEGER BETWEEN 1 AND 7 WHERE  IF JANUARY FIRST IS WEDNESDAY
--      1 = WEDNESDAY, 2 = THURSDAY, ..., 7 = TUESDAY
--
-- EXAMPLE:
--  SELECT PUBLIC.DAY_OF_WEEK_COMPATIBLE_UDF(DATE '2022-01-01'),
--  PUBLIC.DAY_OF_WEEK_COMPATIBLE_UDF(DATE '2023-05-05');
-- RETURNS 1, 6
--
-- EQUIVALENT: TERADATA'S DAYNUMBER_OF_WEEK FUNCTIONALITY
-- EXAMPLE:
--  SELECT DAYNUMBER_OF_WEEK (DATE '2022-01-01', 'COMPATIBLE'),
--  DAYNUMBER_OF_WEEK (DATE '2023-05-05', 'COMPATIBLE');
-- RETURNS 1, 6
-- ======================================================================
CREATE OR REPLACE FUNCTION PUBLIC.TD_DAY_OF_WEEK_COMPATIBLE_UDF(INPUT TIMESTAMP_TZ)
RETURNS INT
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
  IFF(DAYOFWEEKISO(INPUT)=DAYOFWEEKISO(date_from_parts(year(INPUT),1,1)),1,DAYOFWEEKISO(DATEADD(DAY,-DAYOFWEEKISO(date_from_parts(year(INPUT)-1,12,31)),INPUT)))

$$;