-- <copyright file="TD_YEAR_BEGIN_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

-- ======================================================================
-- RETURNS: THE FIRST DAY OF JANUARY WITH ISO YEAR, USED TO CALCULATE THE RESULT OF PUBLIC.YEAR_BEGIN_ISO_UDF
-- PARAMETERS:
--      INPUT: TIMESTAMP_TZ. DATE TO GET JANUARY FIRST USING  ISO YEAR
-- EXAMPLE:
--  SELECT PUBLIC.FIRST_DAY_JANUARY_OF_ISO_UDF(DATE '2022-01-01');
-- RETURNS 2021-01-01
-- ======================================================================
CREATE OR REPLACE FUNCTION PUBLIC.FIRST_DAY_JANUARY_OF_ISO_UDF(INPUT TIMESTAMP_TZ) 
RETURNS DATE 
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    date_from_parts(YEAROFWEEKISO(INPUT),01,01)
$$;

-- ======================================================================
-- DESCRIPTION: UDF THAT REPRODUCES TERADATA'S TD_YEAR_BEGIN(Date,'ISO') FUNCTIONALITY
-- DEPENDING OF DAYOFWEEKISO OF PUBLIC.FIRST_DAY_JANUARY_OF_ISO_UDF ADD OR SUBSTRACT DAYS
-- TO FIND THE MONDAY CLOSER TO PUBLIC.FIRST_DAY_JANUARY_OF_ISO_UDF WHICH WOULD BE THE 
-- FIRST DAY OF YEAR USING ISO CALENDAR
-- PARAMETERS: INPUT: DATE TO GET THE THE FIRST DAY OF YEAR USING ISO CALENDAR
-- RETURNS: THE FIRST DAY OF YEAR USING ISO CALENDAR
--
-- EXAMPLE:
--  SELECT  PUBLIC.YEAR_BEGIN_ISO_UDF(DATE '2022-01-01'),
--  PUBLIC.YEAR_BEGIN_ISO_UDF(DATE '2022-04-12');
-- RETURNS 2021-01-04, 2022-01-03
--
-- EQUIVALENT: TERADATA'S TD_YEAR_BEGIN(Date,'ISO') FUNCTIONALITY
-- EXAMPLE:
--  SELECT TD_YEAR_BEGIN(DATE '2022-01-01', 'ISO'),
--  TD_YEAR_BEGIN(DATE '2022-04-12', 'ISO');
-- RETURNS 2021-01-04, 2022-01-03
-- ======================================================================
CREATE OR REPLACE FUNCTION PUBLIC.YEAR_BEGIN_ISO_UDF(INPUT DATE)
RETURNS DATE 
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
     CASE 
     WHEN DAYOFWEEKISO(FIRST_DAY_JANUARY_OF_ISO_UDF(INPUT))>=5 THEN DATEADD(day,8-DAYOFWEEKISO(FIRST_DAY_JANUARY_OF_ISO_UDF(INPUT)),FIRST_DAY_JANUARY_OF_ISO_UDF(INPUT))
     WHEN DAYOFWEEKISO(FIRST_DAY_JANUARY_OF_ISO_UDF(INPUT))>=2 THEN DATEADD(day,1-DAYOFWEEKISO(FIRST_DAY_JANUARY_OF_ISO_UDF(INPUT)),FIRST_DAY_JANUARY_OF_ISO_UDF(INPUT))
     ELSE FIRST_JUANARY_OF_ISO(INPUT)
     end
$$;


-- ======================================================================
-- DESCRIPTION: UDF THAT REPRODUCES TERADATA'S TD_YEAR_BEGIN(DATE) OR TD_YEAR_BEGIN(DATE, 'COMPATIBLE') FUNCTIONALITY
-- RETURNS: THE FIRST DAY OF THE YEAR
-- PARAMETERS:
--      INPUT: DATE TO GET THE FIRST DAY OF YEAR
--
-- EXAMPLE:
--  SELECT  PUBLIC.TD_YEAR_BEGIN_UDF(DATE '2022-01-01'),
--  PUBLIC.TD_YEAR_BEGIN_UDF(DATE '2022-04-12');
-- RETURNS 2022-01-01, 2022-01-01
--
-- EQUIVALENT: TERADATA'S TD_YEAR_BEGIN FUNCTIONALITY
-- EXAMPLE:
--  SELECT TD_YEAR_BEGIN(DATE '2022-01-01', 'COMPATIBLE'),
--  TD_YEAR_BEGIN(DATE '2022-04-12');
-- RETURNS 2022-01-01, 2022-01-01
-- ======================================================================
CREATE OR REPLACE FUNCTION PUBLIC.TD_YEAR_BEGIN_UDF(INPUT date)
RETURNS DATE 
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
     date_from_parts(year(INPUT),01,01)
$$;