-- <copyright file="TD_YEAR_END_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>


-- ======================================================================
-- RETURNS: THE LAST DAY OF DECEMBER WITH ISO YEAR, USED TO CALCULATE THE RESULT OF PUBLIC.YEAR_END_ISO_UDF
-- PARAMETERS:
--      INPUT: TIMESTAMP_TZ. DATE TO GET DECEMBER LAST DAY USING  ISO YEAR
-- EXAMPLE:
--  SELECT PUBLIC.LAST_DAY_DECEMBER_OF_ISO_UDF(DATE '2022-01-01');
-- RETURNS 2021-12-31
-- ======================================================================
CREATE OR REPLACE FUNCTION PUBLIC.LAST_DAY_DECEMBER_OF_ISO_UDF(INPUT TIMESTAMP_TZ)
RETURNS DATE 
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
    date_from_parts(YEAROFWEEKISO(INPUT),12,31)
$$;

-- ======================================================================
-- DESCRIPTION: UDF THAT REPRODUCES TERADATA'S TD_YEAR_END(Date,'ISO') FUNCTIONALITY
-- DEPENDING OF DAYOFWEEKISO OF PUBLIC.LAST_DAY_DECEMBER_OF_ISO_UDF ADD OR SUBSTRACT DAYS
-- TO FIND THE SUNDAY CLOSER TO PUBLIC.LAST_DAY_DECEMBER_OF_ISO_UDF WHICH WOULD BE THE 
-- LAST DAY OF YEAR USING ISO CALENDAR
-- PARAMETERS: INPUT: DATE TO GET THE THE LAST DAY OF YEAR USING ISO CALENDAR
-- RETURNS: THE LAST DAY OF YEAR USING ISO CALENDAR
--
-- EXAMPLE:
--  SELECT  PUBLIC.YEAR_END_ISO_UDF(DATE '2022-01-01'),
--  PUBLIC.YEAR_END_ISO_UDF(DATE '2022-04-12');
-- RETURNS 2022-01-02, 2023-01-01
--
-- EQUIVALENT: TERADATA'S TD_YEAR_END(Date,'ISO') FUNCTIONALITY
-- EXAMPLE:
--  SELECT TD_YEAR_END(DATE '2022-01-01', 'ISO'),
--  TD_YEAR_END(DATE '2022-04-12', 'ISO');
-- RETURNS 2022-01-02, 2023-01-01
-- ======================================================================
CREATE OR REPLACE FUNCTION PUBLIC.YEAR_END_ISO_UDF(INPUT date)
RETURNS DATE 
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
     CASE 
     WHEN DAYOFWEEKISO(PUBLIC.LAST_DAY_DECEMBER_OF_ISO_UDF(INPUT))<=3 THEN DATEADD(day,-DAYOFWEEKISO(PUBLIC.LAST_DAY_DECEMBER_OF_ISO_UDF(INPUT)),PUBLIC.LAST_DAY_DECEMBER_OF_ISO_UDF(INPUT))
     WHEN DAYOFWEEKISO(PUBLIC.LAST_DAY_DECEMBER_OF_ISO_UDF(INPUT))<=6 THEN DATEADD(day,7-DAYOFWEEKISO(PUBLIC.LAST_DAY_DECEMBER_OF_ISO_UDF(INPUT)),PUBLIC.LAST_DAY_DECEMBER_OF_ISO_UDF(INPUT))
     ELSE PUBLIC.LAST_DAY_DECEMBER_OF_ISO_UDF(INPUT)
     END
$$;

-- ======================================================================
-- DESCRIPTION: UDF THAT REPRODUCES TERADATA'S TD_YEAR_END(DATE) OR TD_YEAR_END(DATE, 'COMPATIBLE') FUNCTIONALITY
-- RETURNS: THE LAST DAY OF THE YEAR
-- PARAMETERS:
--      INPUT: DATE TO GET THE LAST DAY OF YEAR
--
-- EXAMPLE:
--  SELECT  PUBLIC.TD_YEAR_END_UDF(DATE '2022-01-01'),
--  PUBLIC.TD_YEAR_END_UDF(DATE '2022-04-12');
-- RETURNS 2022-12-31, 2022-12-31
--
-- EQUIVALENT: TERADATA'S TD_YEAR_END FUNCTIONALITY
-- EXAMPLE:
--  SELECT TD_YEAR_END(DATE '2022-01-01', 'COMPATIBLE'),
--  TD_YEAR_END(DATE '2022-04-12');
-- RETURNS 2022-12-31, 2022-12-31
-- ======================================================================
CREATE OR REPLACE FUNCTION PUBLIC.TD_YEAR_END_UDF(INPUT date)
RETURNS DATE 
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
     LAST_DAY(INPUT,'year')
$$;
