-- <copyright file="TIMESTAMP_ADD_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

-- =============================================
-- DESCRIPTION: UDF THAT ALLOWS THE ADDITION OF 2 DIFFERENT TIMESTAMPS
-- EQUIVALENT: TERADATA'S TIMESTAMP + TIMESTAMP
-- PARAMETERS:
-- FIRST_DATE: TIMESTAMP_LTZ
-- SECOND_DATE: TIMESTAMP_LTZ
-- RETURNS: A TIMESTAMP RESULTING FROM THE ADDITION OF FIRST_DATE AND SECOND_DATE
-- =============================================
CREATE OR REPLACE FUNCTION PUBLIC.TIMESTAMP_ADD_UDF(FIRST_DATE TIMESTAMP_LTZ, SECOND_DATE TIMESTAMP_LTZ)
RETURNS TIMESTAMP_LTZ
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
	TIMESTAMPADD(YEAR, YEAR(SECOND_DATE), TIMESTAMPADD(MONTH, MONTH(SECOND_DATE), TIMESTAMPADD(DAY, DAY(SECOND_DATE), 
	TIMESTAMPADD(SECOND, SECOND(SECOND_DATE), TIMESTAMPADD(MINUTE, MINUTE(SECOND_DATE), TIMESTAMPADD(HOUR, HOUR(SECOND_DATE), FIRST_DATE))))))
$$;