"""
Auto-generated from: 03_aggregations_pivot_windows.ipynb
Generated by: dvp-notebook-to-script
Generated at: 2026-04-28T18:15:54.986972+00:00
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / '03-tests'))

from dvp_notebook_helper import Notebook


def run(spark=None):
    nb = Notebook("03_aggregations_pivot_windows.ipynb", __file__)

    try:

        # region 001 (markdown) ================================
        nb.cell("001", "markdown")

        # # 03 — Aggregations, Pivot Tables, and Window Functions
        # 
        # **Tasty Bytes Consulting** — financial portfolio analytics demo.
        # 
        # Demonstrates advanced PySpark aggregation patterns over real financial concepts:
        # 
        # - `groupBy` with multiple aggregation functions (trade count, buy/sell notional, distinct assets)
        # - `pivot` to reshape portfolio × asset class from long → wide
        # - Window functions: `row_number`, `rank`, `dense_rank`
        # - Running totals using `rowsBetween(Window.unboundedPreceding, Window.currentRow)`
        # - `lag` and `lead` for month-over-month price comparison
        # - `collect_set` to gather traded assets per portfolio
        # - `rollup` for strategy → asset class → transaction type subtotals
        # endregion 001 ----------------------------------------

        # region 002 ===========================================
        nb.cell("002")

        import sys; sys.path.insert(0, '.')
        from demo_data import create_spark_session, load_all, COMPANY_NAME
        
        _provided_spark = spark is not None
        if not _provided_spark:
            spark = create_spark_session("Aggregations_Pivot_Windows")
        spark.sparkContext.setLogLevel("WARN")
        data = load_all(spark)
        
        transactions_df = data["transactions"]
        portfolios_df   = data["portfolios"]
        assets_df       = data["assets"]
        prices_df       = data["prices"]
        
        from pyspark.sql import functions as F
        from pyspark.sql.window import Window
        
        print(f"Spark version: {spark.version}")
        print(f"Company: {COMPANY_NAME}")
        print(f"Transactions: {transactions_df.count()} rows")
        transactions_df.printSchema()
        # endregion 002 ----------------------------------------

        # region 003 (markdown) ================================
        nb.cell("003", "markdown")

        # ## 1. `groupBy` aggregations — portfolio × transaction type
        # 
        # Aggregate `fct_transactions` by `portfolio_id` and `txn_type` to summarise
        # trade activity: count, total buy/sell notional value (USD), distinct assets
        # traded, and average trade size.  Join `dim_portfolios` for the portfolio name.
        # endregion 003 ----------------------------------------

        # region 004 ===========================================
        nb.cell("004")

        portfolio_txn_summary = (
            transactions_df
            .groupBy("portfolio_id", "txn_type")
            .agg(
                F.count("*").alias("trade_count"),
                F.round(
                    F.sum(
                        F.when(F.col("txn_type") == "buy",
                               F.col("quantity") * F.col("price") * F.col("fx_rate_to_usd"))
                         .otherwise(0.0)
                    ), 2
                ).alias("total_buy_usd"),
                F.round(
                    F.sum(
                        F.when(F.col("txn_type") == "sell",
                               F.col("quantity") * F.col("price") * F.col("fx_rate_to_usd"))
                         .otherwise(0.0)
                    ), 2
                ).alias("total_sell_usd"),
                F.countDistinct("asset_id").alias("distinct_assets"),
                F.round(
                    F.avg(F.col("quantity") * F.col("price") * F.col("fx_rate_to_usd")), 2
                ).alias("avg_trade_size_usd"),
            )
        )
        
        portfolio_summary = (
            portfolio_txn_summary
            .join(portfolios_df.select("portfolio_id", "portfolio_name"), "portfolio_id", "left")
            .select(
                "portfolio_id", "portfolio_name", "txn_type",
                "trade_count", "total_buy_usd", "total_sell_usd",
                "distinct_assets", "avg_trade_size_usd",
            )
            .orderBy("portfolio_id", "txn_type")
        )
        
        print("=== Portfolio x Transaction Type Summary ===")
        portfolio_summary.show(truncate=False)
        # endregion 004 ----------------------------------------

        # region 005 (markdown) ================================
        nb.cell("005", "markdown")

        # ## 2. `pivot` — portfolio notional value by asset class
        # 
        # Reshape `fct_transactions` from long (one row per trade) to wide (one column
        # per asset class) showing total notional USD (`quantity × price × fx_rate_to_usd`).
        # Asset classes: `equity`, `fixed_income`, `alternative`, `cash`.
        # endregion 005 ----------------------------------------

        # region 006 ===========================================
        nb.cell("006")

        # Compute notional value and attach asset_class from dim_assets
        txn_with_class = (
            transactions_df
            .withColumn("notional_usd",
                        F.col("quantity") * F.col("price") * F.col("fx_rate_to_usd"))
            .join(assets_df.select("asset_id", "asset_class"), "asset_id", "left")
        )
        
        # Pivot: portfolio_id → one column per asset_class
        notional_pivot = (
            txn_with_class
            .groupBy("portfolio_id")
            .pivot("asset_class", ["equity", "fixed_income", "alternative", "cash"])
            .agg(F.round(F.sum("notional_usd"), 2))
            .fillna(0.0)
            .join(
                portfolios_df.select("portfolio_id", "portfolio_name", "strategy"),
                "portfolio_id", "left"
            )
            .select(
                "portfolio_id", "portfolio_name", "strategy",
                "equity", "fixed_income", "alternative", "cash",
            )
            .orderBy("portfolio_id")
        )
        
        print("=== Notional USD Pivot: Portfolio x Asset Class ===")
        notional_pivot.show(truncate=False)
        # endregion 006 ----------------------------------------

        # region 007 (markdown) ================================
        nb.cell("007", "markdown")

        # ## 3. Window functions — asset performance ranking
        # 
        # From `fct_daily_prices`, compute each asset's cumulative return relative to its
        # first available month-end close price, then rank all assets within each
        # month-end snapshot using `rank()`, `dense_rank()`, and `row_number()`.
        # endregion 007 ----------------------------------------

        # region 008 ===========================================
        nb.cell("008")

        # Cumulative return from first available close price per asset
        asset_time_window = Window.partitionBy("asset_id").orderBy("price_date")
        
        prices_with_perf = (
            prices_df
            .withColumn("first_close", F.first("close_price").over(asset_time_window))
            .withColumn(
                "pct_return",
                F.round(
                    (F.col("close_price") - F.col("first_close"))
                    / F.col("first_close") * 100,
                    2,
                ),
            )
        )
        
        # Rank assets by pct_return within each month-end snapshot
        month_window = Window.partitionBy("price_date").orderBy(F.desc("pct_return"))
        
        ranked_assets = (
            prices_with_perf
            .withColumn("rank",       F.rank().over(month_window))
            .withColumn("dense_rank", F.dense_rank().over(month_window))
            .withColumn("row_number", F.row_number().over(month_window))
            .join(assets_df.select("asset_id", "ticker", "asset_class"), "asset_id", "left")
            .select(
                "price_date", "ticker", "asset_class",
                "close_price", "pct_return", "rank", "dense_rank", "row_number",
            )
            .orderBy("price_date", "rank")
        )
        
        print("=== Asset Performance Ranking by Month-End ===")
        ranked_assets.show(40, truncate=False)
        
        print("=== Top Performer Each Month ===")
        ranked_assets.filter(F.col("rank") == 1).show(truncate=False)
        # endregion 008 ----------------------------------------

        # region 009 (markdown) ================================
        nb.cell("009", "markdown")

        # ## 4. Running totals, `lag`, and `lead` — AAPL price history
        # 
        # For AAPL (AST-001) demonstrate:
        # - **Running total** of close prices using `rowsBetween(Window.unboundedPreceding, Window.currentRow)`
        # - **Cumulative return** from the first month-end observation
        # - **`lag`**: previous month's close price
        # - **`lead`**: next month's close price (look-ahead)
        # endregion 009 ----------------------------------------

        # region 010 ===========================================
        nb.cell("010")

        aapl_window = Window.partitionBy("asset_id").orderBy("price_date")
        rows_window  = aapl_window.rowsBetween(Window.unboundedPreceding, Window.currentRow)
        
        aapl_ts = (
            prices_df
            .filter(F.col("asset_id") == "AST-001")
            # Previous month close (lag)
            .withColumn("prev_close",       F.lag("close_price", 1).over(aapl_window))
            # Next month close (lead)
            .withColumn("next_month_close", F.lead("close_price", 1).over(aapl_window))
            # Month-over-month USD change
            .withColumn(
                "mom_change_usd",
                F.round(F.col("close_price") - F.col("prev_close"), 2),
            )
            # Month-over-month % change
            .withColumn(
                "mom_change_pct",
                F.when(
                    F.col("prev_close").isNotNull(),
                    F.round(
                        (F.col("close_price") - F.col("prev_close"))
                        / F.col("prev_close") * 100,
                        2,
                    ),
                ).otherwise(F.lit(None)),
            )
            # Running total of close prices (rowsBetween pattern)
            .withColumn(
                "running_total_usd",
                F.round(F.sum("close_price").over(rows_window), 2),
            )
            # Cumulative return from first observation
            .withColumn("first_close", F.first("close_price").over(aapl_window))
            .withColumn(
                "cumulative_return_pct",
                F.round(
                    (F.col("close_price") - F.col("first_close"))
                    / F.col("first_close") * 100,
                    2,
                ),
            )
            .select(
                "price_date", "close_price", "prev_close", "next_month_close",
                "mom_change_usd", "mom_change_pct",
                "running_total_usd", "cumulative_return_pct",
            )
            .orderBy("price_date")
        )
        
        print("=== AAPL (AST-001): Running Total, Lag & Lead ===")
        aapl_ts.show(truncate=False)
        # endregion 010 ----------------------------------------

        # region 011 (markdown) ================================
        nb.cell("011", "markdown")

        # ## 5. `collect_set` — traded assets per portfolio
        # 
        # Aggregate transactions to produce a per-portfolio profile: the set of distinct
        # asset IDs traded, first and last transaction dates, and total transaction count.
        # endregion 011 ----------------------------------------

        # region 012 ===========================================
        nb.cell("012")

        portfolio_profile = (
            transactions_df
            .groupBy("portfolio_id")
            .agg(
                F.collect_set("asset_id").alias("traded_assets"),
                F.min("txn_date").alias("first_trade_date"),
                F.max("txn_date").alias("last_trade_date"),
                F.count("*").alias("total_transactions"),
            )
            .join(
                portfolios_df.select("portfolio_id", "portfolio_name", "strategy"),
                "portfolio_id", "left"
            )
            .select(
                "portfolio_id", "portfolio_name", "strategy",
                "traded_assets", "first_trade_date", "last_trade_date", "total_transactions",
            )
            .orderBy("portfolio_id")
        )
        
        print("=== Portfolio Trading Profile (collect_set) ===")
        portfolio_profile.show(truncate=False)
        # endregion 012 ----------------------------------------

        # region 013 (markdown) ================================
        nb.cell("013", "markdown")

        # ## 6. `rollup` — multi-level subtotals
        # 
        # `rollup` generates subtotals at each level of a hierarchy plus a grand total.
        # Roll up `fct_transactions` by `strategy` → `asset_class` → `txn_type`,
        # joining `dim_portfolios` and `dim_assets` first to attach those dimensions.
        # endregion 013 ----------------------------------------

        # region 014 ===========================================
        nb.cell("014")

        # Enrich transactions with strategy (from portfolios) and asset_class (from assets)
        txn_enriched = (
            transactions_df
            .withColumn("notional_usd",
                        F.col("quantity") * F.col("price") * F.col("fx_rate_to_usd"))
            .join(portfolios_df.select("portfolio_id", "strategy"), "portfolio_id", "left")
            .join(assets_df.select("asset_id", "asset_class"),       "asset_id",     "left")
        )
        
        rollup_df = (
            txn_enriched
            .rollup("strategy", "asset_class", "txn_type")
            .agg(
                F.round(F.sum("notional_usd"), 2).alias("total_notional_usd"),
                F.count("*").alias("trade_count"),
            )
            .withColumn(
                "level",
                F.when(F.col("strategy").isNull(),   "Grand Total")
                 .when(F.col("asset_class").isNull(), "Strategy Subtotal")
                 .when(F.col("txn_type").isNull(),    "Asset Class Subtotal")
                 .otherwise("Detail"),
            )
            .orderBy(
                F.col("strategy").asc_nulls_last(),
                F.col("asset_class").asc_nulls_last(),
                F.col("txn_type").asc_nulls_last(),
            )
        )
        
        print("=== Rollup: Strategy → Asset Class → Transaction Type ===")
        rollup_df.show(50, truncate=False)
        # endregion 014 ----------------------------------------

        # region 015 ===========================================
        nb.cell("015")

        if not _provided_spark:
            spark.stop()
        # endregion 015 ----------------------------------------

        nb.finish()

    except Exception as _e:
        nb.report_error(_e)
        raise


if __name__ == "__main__":
    run()
