-- <copyright file="DATEDIFF_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

-- =========================================================================================================
-- DESCRIPTION: The DATEDIFF_UDF() is used as a template for all the cases when there is a subtraction
-- between a date type and an unknown type and all the cases to get the differences between 2 DATES, or TIMESTAMPS.
-- EQUIVALENT: Oracle DATE - DATE , DATE - FLOAT, TIMESTAMP - FLOAT
-- NOTE: FOR TIMESTAMP - TIMESTAMP PLEASE REFER TO TIMESTAMP_DIFF_UDF()
-- NOTE: TO REPLICATE ORACLE DATE - TIMESTAMP, TIMESTAMP - DATE, USE TIMESTAMP_DIFF_UDF()
-- PARAMETERS:
-- SCENARIO 1:
-- 		FIRST_PARAM: DATE
-- 		SECOND_PARAM: DATE to be subtracted from FIRST_PARAM (for TIMESTAMP - TIMESTAMP, DATE - TIMESTAMP, TIMESTAMP - DATE please refer to TIMESTAMP_DIFF_UDF())
--  RETURNS: The number result of the subtraction between the inputs 
--  EXAMPLE:
-- 		SELECT DATEDIFF_UDF('2022-02-20','2022-02-14'); -- SELECT TO_DATE('2022-02-20','YYYY-MM-DD') - TO_DATE('2022-02-14','YYYY-MM-DD') FROM DUAL; -- RETURNS 6
-- SCENARIO 2:
--      FIRST_PARAM: DATE OR TIMESTAMP
--      SECOND_PARAM: FLOAT to be subtracted TO SECOND_PARAM, the units represent days
--  RETURNS: The DATE result of the subtraction of the inputs
--  EXAMPLE:
--    	SELECT DATEDIFF_UDF('2022-02-14 15:31:00',6); -- SELECT TO_TIMESTAMP('2022-02-14 15:31:00','YYYY-MM-DD HH24:MI:SS') - 6 FROM DUAL; -- RETURNS '2022-02-08'
-- =========================================================================================================
CREATE OR REPLACE FUNCTION PUBLIC.DATEDIFF_UDF(FIRST_PARAM DATE, SECOND_PARAM DATE)
RETURNS INTEGER
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
	FIRST_PARAM - SECOND_PARAM
$$;

CREATE OR REPLACE FUNCTION PUBLIC.DATEDIFF_UDF(FIRST_PARAM DATE, SECOND_PARAM TIMESTAMP)
RETURNS INTEGER
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
	DATEDIFF(ms, SECOND_PARAM, FIRST_PARAM) / 3600000 / 24
$$;

CREATE OR REPLACE FUNCTION PUBLIC.DATEDIFF_UDF(FIRST_PARAM DATE, SECOND_PARAM INTEGER)
RETURNS DATE
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
	DATEADD(day,SECOND_PARAM*-1 ,FIRST_PARAM)
$$;

CREATE OR REPLACE FUNCTION PUBLIC.DATEDIFF_UDF(FIRST_PARAM TIMESTAMP, SECOND_PARAM TIMESTAMP)
RETURNS INTEGER
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
	DATEDIFF(ms, SECOND_PARAM, FIRST_PARAM) / 3600000 / 24
$$;

CREATE OR REPLACE FUNCTION PUBLIC.DATEDIFF_UDF(FIRST_PARAM TIMESTAMP, SECOND_PARAM DATE)
RETURNS INTEGER
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
	DATEDIFF(ms, SECOND_PARAM, FIRST_PARAM) / 3600000 / 24
$$;
       
CREATE OR REPLACE FUNCTION PUBLIC.DATEDIFF_UDF(FIRST_PARAM TIMESTAMP, SECOND_PARAM NUMBER)
RETURNS TIMESTAMP
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
	DATEADD(ms, SECOND_PARAM*3600000*-24, FIRST_PARAM)
$$;
       
CREATE OR REPLACE FUNCTION PUBLIC.DATEDIFF_UDF(FIRST_PARAM TIMESTAMP, SECOND_PARAM VARCHAR)
RETURNS TIMESTAMP
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
  SELECT PUBLIC.VARCHAR_TO_TIMESTAMP_UDF(FIRST_PARAM, SECOND_PARAM, -1)
$$;