-- <copyright file="FETCH_BULK_COLLECTION_RECORDS_UDP.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

CREATE OR REPLACE PROCEDURE PUBLIC.FETCH_BULK_COLLECTION_RECORDS_UDP(CURSOR OBJECT, LIMIT FLOAT, COLUMN_NAMES ARRAY)
RETURNS OBJECT
LANGUAGE JAVASCRIPT
<SnowConvertVersionComment>
EXECUTE AS CALLER
AS
$$
  var objectConstructArgs = [];
  if (COLUMN_NAMES) {
    for (let i = 0 ; i < COLUMN_NAMES.length ; i++) {
      objectConstructArgs.push("'" + COLUMN_NAMES[i] + "'");
      objectConstructArgs.push('$' + (i + 1));
    }
  } else {
    objectConstructArgs.push('*');
  }
  var limitValue = LIMIT ?? 'NULL';
  var query = `SELECT ARRAY_AGG(OBJECT_CONSTRUCT(${objectConstructArgs.join(', ')})) FROM (SELECT * FROM ${CURSOR.NAME}_TEMP_TABLE LIMIT ${limitValue} OFFSET ${CURSOR.ROWCOUNT})`;
  var stmt = snowflake.createStatement({ sqlText: query});
  var resultSet = stmt.execute();
  resultSet.next();
  CURSOR.RESULT = resultSet.getColumnValue(1);
  CURSOR.ROWCOUNT += CURSOR.RESULT.length;
  CURSOR.FOUND = CURSOR.RESULT.length > 0;
  CURSOR.NOTFOUND = !CURSOR.FOUND;
  return CURSOR;
$$;

CREATE OR REPLACE PROCEDURE PUBLIC.FETCH_BULK_COLLECTION_RECORDS_UDP(CURSOR OBJECT)
RETURNS OBJECT
LANGUAGE SQL
<SnowConvertVersionComment>
EXECUTE AS CALLER
AS
$$
  DECLARE
    RESULT OBJECT;
  BEGIN
    RESULT := (CALL PUBLIC.FETCH_BULK_COLLECTION_RECORDS_UDP(:CURSOR, NULL, NULL));
    RETURN :RESULT;
  END;
$$;

CREATE OR REPLACE PROCEDURE PUBLIC.FETCH_BULK_COLLECTION_RECORDS_UDP(CURSOR OBJECT, LIMIT INTEGER)
RETURNS OBJECT
LANGUAGE SQL
<SnowConvertVersionComment>
EXECUTE AS CALLER
AS
$$
  DECLARE
    RESULT OBJECT;
  BEGIN
    RESULT := (CALL PUBLIC.FETCH_BULK_COLLECTION_RECORDS_UDP(:CURSOR, :LIMIT, NULL));
    RETURN :RESULT;
  END;
$$;

CREATE OR REPLACE PROCEDURE PUBLIC.FETCH_BULK_COLLECTION_RECORDS_UDP(CURSOR OBJECT, COLUMN_NAMES ARRAY)
RETURNS OBJECT
LANGUAGE SQL
<SnowConvertVersionComment>
EXECUTE AS CALLER
AS
$$
  DECLARE
    RESULT OBJECT;
  BEGIN
    RESULT := (CALL PUBLIC.FETCH_BULK_COLLECTION_RECORDS_UDP(:CURSOR, NULL, :COLUMN_NAMES));
    RETURN :RESULT;
  END;
$$;