-- <copyright file="OPEN_BULK_CURSOR_UDP.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

CREATE OR REPLACE PROCEDURE PUBLIC.OPEN_BULK_CURSOR_UDP(CURSOR OBJECT, BINDINGS ARRAY)
RETURNS OBJECT
LANGUAGE JAVASCRIPT
<SnowConvertVersionComment>
EXECUTE AS CALLER
AS
$$
  var query = `CREATE OR REPLACE TEMPORARY TABLE ${CURSOR.NAME}_TEMP_TABLE AS ${CURSOR.QUERY}`;
  snowflake.execute({ sqlText: query, binds: BINDINGS });
  CURSOR.ROWCOUNT = 0;
  CURSOR.ISOPEN = true;
  return CURSOR;
$$;

CREATE OR REPLACE PROCEDURE PUBLIC.OPEN_BULK_CURSOR_UDP(CURSOR OBJECT)
RETURNS OBJECT
LANGUAGE SQL
<SnowConvertVersionComment>
EXECUTE AS CALLER
AS
$$
  DECLARE
    RESULT OBJECT;
  BEGIN
    RESULT := (CALL PUBLIC.OPEN_BULK_CURSOR_UDP(:CURSOR, NULL));
    RETURN :RESULT;
  END;
$$;