-- <copyright file="TO_CHAR_UDF.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

CREATE OR REPLACE FUNCTION PUBLIC.TO_CHAR_UDF(INPUT_VALUE TIMESTAMP, FORMAT_STRING VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
IMMUTABLE
<SnowConvertVersionComment>
AS
$$
CASE FORMAT_STRING
    WHEN 'AD' OR 'BC' THEN IFF(YEAR(INPUT_VALUE) < 0, 'BC', 'AD')
    WHEN 'A.D.' OR 'B.C.' THEN IFF(YEAR(INPUT_VALUE) < 0, 'B.C.', 'A.D.')
    WHEN 'CC' OR 'SCC' THEN IFF(MOD(YEAR(INPUT_VALUE), 100) = 0, SUBSTR(TO_CHAR(INPUT_VALUE, 'YYYY'), 1, 2), SUBSTR(TO_CHAR(DATEADD(YEAR, 100, INPUT_VALUE), 'YYYY'), 1, 2))
    WHEN 'D' THEN TO_CHAR(DAYOFWEEK(INPUT_VALUE) + 1)
    WHEN 'DAY' THEN UPPER(PUBLIC.FULL_DAY_NAME_UDF(INPUT_VALUE))
    WHEN 'DDD' THEN TO_CHAR(DAYOFYEAR(INPUT_VALUE))
    WHEN 'DD-MON-RR' THEN UPPER(TO_CHAR(INPUT_VALUE,'DD-MON-YY'))
    WHEN 'DL' THEN PUBLIC.FULL_DAY_NAME_UDF(INPUT_VALUE) || TO_CHAR(INPUT_VALUE, ', MMMM DD, YYYY')
    WHEN 'DS' THEN LTRIM(TO_CHAR(INPUT_VALUE, 'MM'), '0') || '/' || LTRIM(TO_CHAR(INPUT_VALUE, 'DD'), '0') || '/' || TO_CHAR(INPUT_VALUE, 'YYYY')
    WHEN 'DY' THEN UPPER(TO_CHAR(INPUT_VALUE, 'DY'))
    WHEN 'I' THEN SUBSTR(TO_CHAR(INPUT_VALUE, 'YYYY'), 4, 1)
    WHEN 'IW' THEN TO_CHAR(WEEKISO(INPUT_VALUE))
    WHEN 'IY' THEN TO_CHAR(INPUT_VALUE, 'YY')
    WHEN 'IYY' OR 'IYYY' THEN SUBSTR(TO_CHAR(INPUT_VALUE, 'YYYY'), 2, 3)
    WHEN 'J' THEN PUBLIC.DATE_TO_JULIAN_DAYS_UDF(INPUT_VALUE)::VARCHAR
    WHEN 'MON' THEN UPPER(TO_CHAR(INPUT_VALUE, 'MON'))
    WHEN 'MONTH' THEN UPPER(TO_CHAR(INPUT_VALUE, 'MMMM'))
    WHEN 'Q' THEN TO_CHAR(QUARTER(INPUT_VALUE))
    WHEN 'RM' THEN GET(['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X', 'XI', 'XII'], MONTH(INPUT_VALUE) - 1)::VARCHAR
    WHEN 'RR' THEN TO_CHAR(INPUT_VALUE, 'YY')
    WHEN 'RR-MON-DD' THEN TO_CHAR(INPUT_VALUE,'YY-MON-DD')
    WHEN 'RRRR' THEN TO_CHAR(INPUT_VALUE, 'YYYY')
    WHEN 'SS' THEN (CASE WHEN SECOND(INPUT_VALUE) = 0 THEN '00' WHEN SECOND(INPUT_VALUE) < 10 THEN '0' || TO_CHAR(SECOND(INPUT_VALUE)) ELSE TO_CHAR(SECOND(INPUT_VALUE)) END)
    WHEN 'SSSS' THEN TO_CHAR(SECOND(INPUT_VALUE) + MINUTE(INPUT_VALUE) * 60 + HOUR(INPUT_VALUE) * 3600)
    WHEN 'SYYYY' THEN TO_CHAR(INPUT_VALUE, 'YYYY')
    WHEN 'TS' THEN TO_CHAR(INPUT_VALUE, 'HH:MI:SS PM')
    WHEN 'W' THEN TRUNC(DAYOFMONTH(INPUT_VALUE) / 7 + 1)::VARCHAR
    WHEN 'WW' THEN LPAD(TRUNC(DAYOFYEAR(INPUT_VALUE) / 7 + 1), 2, 0)
    WHEN 'Y' THEN SUBSTR(TO_CHAR(INPUT_VALUE, 'YYYY'), 4, 1)
    WHEN 'Y,YYY' THEN SUBSTR(TO_CHAR(YEAR(INPUT_VALUE)), 1, 1) || ',' || SUBSTR(TO_CHAR(YEAR(INPUT_VALUE)), 2, 3)
    WHEN 'YEAR' OR 'SYEAR' THEN PUBLIC.YEAR_NAME_UDF(INPUT_VALUE)
    WHEN 'YYY' THEN SUBSTR(TO_CHAR(INPUT_VALUE, 'YYYY'), 2, 3)
ELSE
    'UNSUPPORTED FORMAT'
END
$$;