"""
DVP Notebook Helper - Runtime utility for converted notebook scripts.

This module is imported by every .ipynb.py script generated by
dvp-notebook-to-script. It provides cell tracking, execution logging,
error reporting, and magic command handling.

Logging is configured via Python's standard logging module.
Default level is INFO. Set to DEBUG to see cell-level transitions:
    logging.getLogger("dvp.notebook").setLevel(logging.DEBUG)
"""

import inspect
import logging
import traceback
from datetime import datetime, timezone
from pathlib import Path

_LOG_FORMAT = "%(asctime)s [%(levelname)s] %(name)s - %(message)s"
_DATE_FORMAT = "%H:%M:%S"


def _setup_root_logger():
    """Configure the dvp.notebook logger with sensible defaults."""
    logger = logging.getLogger("dvp.notebook")
    if not logger.handlers:
        handler = logging.StreamHandler()
        handler.setFormatter(logging.Formatter(_LOG_FORMAT, datefmt=_DATE_FORMAT))
        logger.addHandler(handler)
        logger.setLevel(logging.INFO)
    return logger


_setup_root_logger()


class Notebook:
    """Runtime helper for converted notebook scripts."""

    # Converted file extensions in resolution priority order
    _CONVERTED_EXTENSIONS = [".dbx.py", ".ipynb.py"]

    def __init__(self, name: str, caller_file: str = None):
        """
        Initialize the notebook helper and log execution start.

        Args:
            name: Original notebook filename (e.g., "1_dataprep.ipynb")
            caller_file: __file__ of the calling script, used to resolve
                         relative %run references. Pass ``__file__`` from
                         the converted notebook.
        """
        self.name = name
        self._current_cell = None
        self._cell_type = None
        self._start_time = datetime.now(timezone.utc)
        self._logger = logging.getLogger(f"dvp.notebook.{name}")
        self._caller_dir = Path(caller_file).resolve().parent if caller_file else None

        self._logger.info("Starting execution of notebook %s", self.name)

    def cell(self, number: str, cell_type: str = "code"):
        """
        Mark the start of a notebook cell.

        Called at the beginning of each cell's code to track execution
        progress. If an error occurs, report_error() uses this to identify
        which cell failed.

        Args:
            number: Cell number as zero-padded string (e.g., "001", "012")
            cell_type: One of "code", "markdown", "sql"
        """
        self._current_cell = number
        self._cell_type = cell_type
        self._logger.debug("Starting execution of Cell %s (%s)", number, cell_type)

    def magic(self, kind: str, args: str):
        """
        Handle a Jupyter magic command.

        Converted from IPython magic syntax:
          !pip install x      -> nb.magic("!", "pip install x")
          %matplotlib inline  -> nb.magic("%matplotlib", "inline")
          %%time              -> nb.magic("%%time", "")

        Args:
            kind: Magic type (e.g., "!", "%matplotlib", "%%time")
            args: Arguments passed to the magic command
        """
        self._logger.info("MAGIC [%s]: %s", kind, args)

    # Marker that the converter embeds in flat scripts
    _FLAT_MARKER = "# DVP:FLAT"

    def run(self, notebook_ref: str, params: str = ""):
        """
        Execute another converted notebook via %run.

        Resolves the reference relative to the calling notebook's directory,
        reads the converted file, and ``exec()``s it into the caller's
        globals — matching Databricks' shared-namespace behavior.

        The target script must be a *flat* script (generated with
        ``flat=True``, no ``def run():`` wrapper). If it's wrapped, a
        warning is emitted because the exec would only define the ``run``
        function without executing the cell code.

        Args:
            notebook_ref: Relative path to the target notebook (e.g., "../config")
            params: Parameter string (e.g., '$brand="plk"') — logged but not
                    injected (Databricks widget params are not emulated)
        """
        if params:
            self._logger.info("RUN [%%run]: %s %s", notebook_ref, params)
        else:
            self._logger.info("RUN [%%run]: %s", notebook_ref)

        resolved = self._resolve_notebook(notebook_ref)
        if resolved is None:
            self._logger.warning(
                "%%run target not found: %s (searched from %s)",
                notebook_ref, self._caller_dir,
            )
            return

        source = resolved.read_text(encoding="utf-8")

        if self._FLAT_MARKER not in source:
            self._logger.warning(
                "%%run target %s is NOT a flat script. "
                "Variables will not be shared with the caller. "
                "Re-run the converter so this notebook is detected as a %%run target.",
                resolved.name,
            )

        self._logger.info("exec %%run: %s", resolved)
        caller_globals = inspect.stack()[1][0].f_globals
        exec(compile(source, str(resolved), "exec"), caller_globals)

    def _resolve_notebook(self, notebook_ref: str) -> Path | None:
        """
        Resolve a %run reference to a converted file on disk.

        Tries each converted extension (.dbx.py, .ipynb.py) against the
        reference path relative to the caller's directory.
        """
        if self._caller_dir is None:
            return None

        base = self._caller_dir / notebook_ref
        for ext in self._CONVERTED_EXTENSIONS:
            # e.g. ./pipeline_config → pipeline_config.dbx.py
            candidate = base.with_name(base.name + ext)
            if candidate.exists():
                return candidate
            # Also try if ref already has .py: ../config.py → config.dbx.py
            if base.suffix == ".py":
                candidate = base.with_suffix(ext)
                if candidate.exists():
                    return candidate
        return None

    def finish(self):
        """Log successful completion of the notebook execution."""
        elapsed = (datetime.now(timezone.utc) - self._start_time).total_seconds()
        self._logger.info(
            "Execution of notebook %s finished successfully (%.1fs)", self.name, elapsed
        )

    def report_error(self, exception: Exception):
        """
        Report which cell caused an error, with full traceback.

        Args:
            exception: The caught exception
        """
        elapsed = (datetime.now(timezone.utc) - self._start_time).total_seconds()
        self._logger.error(
            "ERROR in notebook %s - Cell %s after %.1fs",
            self.name,
            self._current_cell,
            elapsed,
            exc_info=True,
        )
